In [1]:
import requests as rq
from bs4 import BeautifulSoup
import pandas as pd
import re

In [2]:
Mens_olympic_skiing = pd.read_csv("Mens_olympic_skiing.csv")

In [3]:
women_olypmics_skiing = pd.read_csv("women_olypmics_skiing.csv")

In [4]:
women_olypmics_skiing.head()

,Unnamed: 0,Age,Athlete,Country,Medal,NOC,Rank,Time,Year,Type,Gender
0,0,24,Hedy Schlunegger,Switzerland,Gold,SUI,1.0,2:28.3,1948,Downhill,Women
1,1,20,Trude Jochum-Beiser,Austria,Silver,AUT,2.0,2:29.1,1948,Downhill,Women
2,2,22,Resi Hammerer,Austria,Bronze,AUT,3.0,2:30.2,1948,Downhill,Women
3,3,27,Celina Seghi,Italy,NaN,ITA,4.0,2:31.1,1948,Downhill,Women
4,4,28,Lina Mittner,Switzerland,NaN,SUI,5.0,2:31.2,1948,Downhill,Women

In [5]:
Mens_olympic_skiing.head()

,Unnamed: 0,Age,Athlete,Country,Medal,NOC,Rank,Time,Year,Type,Gender
0,0,22.0,Henri Oreiller,France,Gold,FRA,1,2:55.0,1948,DownHill,Male
1,1,26.0,Franz Gabl,Austria,Silver,AUT,2,2:59.1,1948,DownHill,Male
2,2,27.0,Karl Molitor,Switzerland,Bronze,SUI,3,3:00.3,1948,DownHill,Male
3,3,23.0,Ralph Olinger,Switzerland,Bronze,SUI,3,3:00.3,1948,DownHill,Male
4,4,22.0,Egon SchÃ¶pf,Austria,NaN,AUT,5,3:01.2,1948,DownHill,Male

In [6]:
olympic_skiing = Mens_olympic_skiing.append(women_olypmics_skiing)

In [7]:
olympic_skiing.drop("Unnamed: 0", 1, inplace = True)

In [8]:
olympic_skiing["test"] = olympic_skiing["Year"].isnull()

In [9]:
olympic_skiing[olympic_skiing["test"] == True]

Empty DataFrame
Columns: [Age, Athlete, Country, Medal, NOC, Rank, Time, Year, Type, Gender, test]
Index: []

In [10]:
olympic_skiing.head()

,Age,Athlete,Country,Medal,NOC,Rank,Time,Year,Type,Gender,test
0,22.0,Henri Oreiller,France,Gold,FRA,1,2:55.0,1948,DownHill,Male,False
1,26.0,Franz Gabl,Austria,Silver,AUT,2,2:59.1,1948,DownHill,Male,False
2,27.0,Karl Molitor,Switzerland,Bronze,SUI,3,3:00.3,1948,DownHill,Male,False
3,23.0,Ralph Olinger,Switzerland,Bronze,SUI,3,3:00.3,1948,DownHill,Male,False
4,22.0,Egon SchÃ¶pf,Austria,NaN,AUT,5,3:01.2,1948,DownHill,Male,False

In [11]:
olympic_skiing = olympic_skiing.sort_values(by = "Year", ascending = True)

In [12]:
olympic_skiing_1 = olympic_skiing.sort_values(by = "Year", ascending = False)

In [13]:
olympic_skiing["Type"] = olympic_skiing["Type"].str.replace("Combined", "Combine")

In [14]:
olympic_skiing["Type"] = olympic_skiing["Type"].str.replace("DownHill", "Downhill")

In [15]:
olympic_skiing_1.to_csv("olympic_skiing_1.csv")

In [16]:
olympic_skiing["Time_start"] = "0:00.0"

In [17]:
olympic_skiing.rename(columns={'Time':'Time_end'}, inplace=True)

In [18]:
olympic_skiing["Time_end"] = olympic_skiing["Time_end"].str.replace("[", "").str.replace("]", "")

In [19]:
olympic_skiing = olympic_skiing[olympic_skiing["Time_end"] != "DQ"]
olympic_skiing = olympic_skiing[olympic_skiing["Time_end"] != "DNF"]

In [20]:
olympic_skiing.dropna(subset=["Time_end"], inplace = True)

In [21]:
olympic_skiing["test_time"] = olympic_skiing["Time_end"].str.contains(":")

In [22]:
olympic_skiing_seconds = olympic_skiing[olympic_skiing["test_time"] == False]

In [23]:
olympic_skiing_seconds

,Age,Athlete,Country,Medal,NOC,Rank,Time_end,Year,Type,Gender,test,Time_start,test_time
4878,18.0,Vittorio Chierroni,Italy,NaN,ITA,18.0,80.8,1936,Combine,Male,False,0:00.0,False
4862,25.0,Gustav Lantschner,Germany,Silver,GER,2.0,96.26,1936,Combine,Male,False,0:00.0,False
4863,23.0,Ãmile Allais,France,Bronze,FRA,3.0,94.69,1936,Combine,Male,False,0:00.0,False
4864,24.0,Birger Ruud,Norway,NaN,NOR,4.0,93.38,1936,Combine,Male,False,0:00.0,False
4865,22.0,Roman WÃ¶rndle,Germany,NaN,GER,5.0,91.16,1936,Combine,Male,False,0:00.0,False
4866,17.0,Rudi Cranz,Germany,NaN,GER,6.0,91.03,1936,Combine,Male,False,0:00.0,False
4867,22.0,Cinto Sertorelli,Italy,NaN,ITA,7.0,90.39,1936,Combine,Male,False,0:00.0,False
4868,34.0,Alf Konningen,Norway,NaN,NOR,8.0,90.06,1936,Combine,Male,False,0:00.0,False
4869,25.0,Per Fossum,Norway,NaN,NOR,9.0,88.12,1936,Combine,Male,False,0:00.0,False
4870,21.0,"Dick Durrance, Jr.",United States,NaN,USA,10.0,87.74,1936,Combine,Male,False,0:00.0,False
4871,20.0,Maurice Lafforgue,France,NaN,FRA,11.0,85.83,1936,Combine,Male,False,0:00.0,False
4872,21.0,Peter Lunn,Great Britain,NaN,GBR,12.0,83.82,1936,Combine,Male,False,0:00.0,False
4873,25.0,George Page,United States,NaN,USA,13.0,82.85,1936,Combine,Male,False,0:00.0,False
4874,20.0,James Palmer-Tomkinson,Great Britain,NaN,GBR,14.0,82.52,1936,Combine,Male,False,0:00.0,False
4875,22.0,Ciril PraÄek,Yugoslavia,NaN,YUG,15.0,81.54,1936,Combine,Male,False,0:00.0,False
4876,20.0,Walter Hollmann,Czechoslovakia,NaN,TCH,16.0,81.01,1936,Combine,Male,False,0:00.0,False
4877,21.0,Adriano Guarnieri,Italy,NaN,ITA,17.0,80.94,1936,Combine,Male,False,0:00.0,False
4879,21.0,LÃ¡szlÃ³ Szalay,Hungary,NaN,HUN,19.0,79.68,1936,Combine,Male,False,0:00.0,False
4880,27.0,BronisÅaw Czech,Poland,NaN,POL,20.0,79.41,1936,Combine,Male,False,0:00.0,False
4881,21.0,Johann Knahl,Czechoslovakia,NaN,TCH,21.0,78.41,1936,Combine,Male,False,0:00.0,False
4882,24.0,Roland Allard,France,NaN,FRA,22.0,77.86,1936,Combine,Male,False,0:00.0,False
4883,26.0,"Robert Livermore, Jr.",United States,NaN,USA,23.0,77.18,1936,Combine,Male,False,0:00.0,False
4884,23.0,Horst Scheeser,Romania,NaN,ROU,24.0,76.55,1936,Combine,Male,False,0:00.0,False
4861,27.0,Franz PfnÃ¼r,Germany,Gold,GER,1.0,99.25,1936,Combine,Male,False,0:00.0,False
707,21.0,Christl Cranz,Germany,Gold,GER,1,97.06,1936,Combine,Women,False,0:00.0,False
708,18.0,KÃ¤the Grasegger,Germany,Silver,GER,2,95.26,1936,Combine,Women,False,0:00.0,False
709,16.0,Laila Schou Nilsen,Norway,Bronze,NOR,3,93.48,1936,Combine,Women,False,0:00.0,False
733,19.0,Clarita Heath,United States,NaN,USA,27,59.89,1936,Combine,Women,False,0:00.0,False
732,30.0,Karin Peckert-Forsmann,Estonia,NaN,EST,26,62.31,1936,Combine,Women,False,0:00.0,False
731,22.0,Helen Blane,Great Britain,NaN,GBR,25,64.84,1936,Combine,Women,False,0:00.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5065,25.0,Jean-Luc CrÃ©tier,France,NaN,FRA,4.0,18.97,1992,Combine,Male,False,0:00.0,False
5066,28.0,Markus Wasmeier,Germany,NaN,GER,5.0,32.77,1992,Combine,Male,False,0:00.0,False
5067,22.0,Kristian Ghedina,Italy,NaN,ITA,6.0,38.96,1992,Combine,Male,False,0:00.0,False
5068,25.0,Ole Kristian Furuseth,Norway,NaN,NOR,7.0,40.47,1992,Combine,Male,False,0:00.0,False
5069,25.0,Xavier Gigandet,Switzerland,NaN,SUI,8.0,41.21,1992,Combine,Male,False,0:00.0,False
5070,20.0,Takuya Ishioka,Japan,NaN,JPN,9.0,51.83,1992,Combine,Male,False,0:00.0,False
5071,27.0,Lasse Arnesen,Norway,NaN,NOR,10.0,51.93,1992,Combine,Male,False,0:00.0,False
5072,25.0,Jan Einar Thorsen,Norway,NaN,NOR,11.0,52.75,1992,Combine,Male,False,0:00.0,False
828,18.0,Tetiana Lebedeva,Unified Team,NaN,EUN,18,111.34,1992,Combine,Women,False,0:00.0,False
827,16.0,Emma Carrick-Anderson,Great Britain,NaN,GBR,17,107.61,1992,Combine,Women,False,0:00.0,False
826,18.0,Morena Gallizio,Italy,NaN,ITA,16,93.21,1992,Combine,Women,False,0:00.0,False
825,24.0,Ä½udmila MilanovÃ¡,Czechoslovakia,NaN,TCH,15,76.28,1992,Combine,Women,False,0:00.0,False
824,24.0,Heidi Zeller-BÃ¤hler,Switzerland,NaN,SUI,14,69.07,1992,Combine,Women,False,0:00.0,False
823,21.0,Emi Kawabata,Japan,NaN,JPN,13,66.1,1992,Combine,Women,False,0:00.0,False
822,20.0,Svetlana Gladysheva,Unified Team,NaN,EUN,12,61.25,1992,Combine,Women,False,0:00.0,False
821,21.0,Krista Schmidinger,United States,NaN,USA,11,51.56,1992,Combine,Women,False,0:00.0,False
820,21.0,RÃ©gine Cavagnoud,France,NaN,FRA,10,51.13,1992,Combine,Women,False,0:00.0,False
819,24.0,Miriam Vogt,Germany,NaN,GER,9,48.52,1992,Combine,Women,False,0:00.0,False
817,24.0,NataÅ¡a Bokal,Slovenia,NaN,SLO,7,42.6,1992,Combine,Women,False,0:00.0,False
816,24.0,Michelle McKendry-Ruthven,Canada,NaN,CAN,6,39.02,1992,Combine,Women,False,0:00.0,False
815,26.0,Anne Berge,Norway,NaN,NOR,5,35.28,1992,Combine,Women,False,0:00.0,False
814,24.0,Chantal Bournissen,Switzerland,NaN,SUI,4,24.98,1992,Combine,Women,False,0:00.0,False
813,23.0,Florence Masnada,France,Bronze,FRA,3,21.38,1992,Combine,Women,False,0:00.0,False
812,24.0,Anita Wachter,Austria,Silver,AUT,2,19.39,1992,Combine,Women,False,0:00.0,False
811,22.0,Petra Kronberger,Austria,Gold,AUT,1,2.55,1992,Combine,Women,False,0:00.0,False
818,23.0,Lucia MedzihradskÃ¡,Czechoslovakia,NaN,TCH,8,47.43,1992,Combine,Women,False,0:00.0,False
829,17.0,Svetlana Novikova,Unified Team,NaN,EUN,19,122.48,1992,Combine,Women,False,0:00.0,False
830,19.0,Birgit Heeb-Batliner,Liechtenstein,NaN,LIE,20,164.25,1992,Combine,Women,False,0:00.0,False
832,20.0,Astrid LÃ¸demel,Norway,NaN,NOR,22,210.94,1992,Combine,Women,False,0:00.0,False
831,22.0,Carolina Eiras,Argentina,NaN,ARG,21,184.96,1992,Combine,Women,False,0:00.0,False

In [24]:
"0:" + olympic_skiing_seconds["Time_end"]

4878      0:80.8
4862     0:96.26
4863     0:94.69
4864     0:93.38
4865     0:91.16
4866     0:91.03
4867     0:90.39
4868     0:90.06
4869     0:88.12
4870     0:87.74
4871     0:85.83
4872     0:83.82
4873     0:82.85
4874     0:82.52
4875     0:81.54
4876     0:81.01
4877     0:80.94
4879     0:79.68
4880     0:79.41
4881     0:78.41
4882     0:77.86
4883     0:77.18
4884     0:76.55
4861     0:99.25
707      0:97.06
708      0:95.26
709      0:93.48
733      0:59.89
732      0:62.31
731      0:64.84
          ...
5065     0:18.97
5066     0:32.77
5067     0:38.96
5068     0:40.47
5069     0:41.21
5070     0:51.83
5071     0:51.93
5072     0:52.75
828     0:111.34
827     0:107.61
826      0:93.21
825      0:76.28
824      0:69.07
823       0:66.1
822      0:61.25
821      0:51.56
820      0:51.13
819      0:48.52
817       0:42.6
816      0:39.02
815      0:35.28
814      0:24.98
813      0:21.38
812      0:19.39
811       0:2.55
818      0:47.43
829     0:122.48
830     0:164.25
832     0:210.94
831     0:184.96
Name: Time_end, Length: 267, dtype: object

In [25]:
olympic_skiing.sort_values(by = "Time_end", ascending = False)

,Age,Athlete,Country,Medal,NOC,Rank,Time_end,Year,Type,Gender,test,Time_start,test_time
5016,23.0,Armin Bittner,West Germany,NaN,FRG,11.0,99.65,1988,Combine,Male,False,0:00.0,False
4861,27.0,Franz PfnÃ¼r,Germany,Gold,GER,1.0,99.25,1936,Combine,Male,False,0:00.0,False
707,21.0,Christl Cranz,Germany,Gold,GER,1,97.06,1936,Combine,Women,False,0:00.0,False
4862,25.0,Gustav Lantschner,Germany,Silver,GER,2.0,96.26,1936,Combine,Male,False,0:00.0,False
5015,23.0,Niklas Henning,Sweden,NaN,SWE,10.0,96.25,1988,Combine,Male,False,0:00.0,False
708,18.0,KÃ¤the Grasegger,Germany,Silver,GER,2,95.26,1936,Combine,Women,False,0:00.0,False
5014,21.0,Finn Christian Jagge,Norway,NaN,NOR,9.0,95.21,1988,Combine,Male,False,0:00.0,False
4863,23.0,Ãmile Allais,France,Bronze,FRA,3.0,94.69,1936,Combine,Male,False,0:00.0,False
709,16.0,Laila Schou Nilsen,Norway,Bronze,NOR,3,93.48,1936,Combine,Women,False,0:00.0,False
4864,24.0,Birger Ruud,Norway,NaN,NOR,4.0,93.38,1936,Combine,Male,False,0:00.0,False
826,18.0,Morena Gallizio,Italy,NaN,ITA,16,93.21,1992,Combine,Women,False,0:00.0,False
783,22.0,Sylvia Eder,Austria,NaN,AUT,12,92.86,1988,Combine,Women,False,0:00.0,False
710,18.0,Erna Steuri,Switzerland,NaN,SUI,4,92.36,1936,Combine,Women,False,0:00.0,False
711,29.0,Hadi Pfeifer,Germany,NaN,GER,5,91.85,1936,Combine,Women,False,0:00.0,False
4865,22.0,Roman WÃ¶rndle,Germany,NaN,GER,5.0,91.16,1936,Combine,Male,False,0:00.0,False
4866,17.0,Rudi Cranz,Germany,NaN,GER,6.0,91.03,1936,Combine,Male,False,0:00.0,False
5082,24.0,Paul Accola,Switzerland,NaN,SUI,21.0,90.96,1992,Combine,Male,False,0:00.0,False
4867,22.0,Cinto Sertorelli,Italy,NaN,ITA,7.0,90.39,1936,Combine,Male,False,0:00.0,False
4868,34.0,Alf Konningen,Norway,NaN,NOR,8.0,90.06,1936,Combine,Male,False,0:00.0,False
4934,28.0,Hans Nogler,Austria,NaN,AUT,8.0,9.96,1948,Combine,Male,False,0:00.0,False
750,25.0,Anneliese Schuh-Proxauf,Austria,NaN,AUT,7,9.76,1948,Combine,Women,False,0:00.0,False
4933,30.0,Vittorio Chierroni,Italy,NaN,ITA,7.0,9.69,1948,Combine,Male,False,0:00.0,False
4932,28.0,Hans Hansson,Sweden,NaN,SWE,6.0,9.31,1948,Combine,Male,False,0:00.0,False
239,29.0,Christos Papageorgiou,Greece,NaN,GRE,47,8:03.2,1956,Downhill,Male,False,0:00.0,True
4992,19.0,Lajos MÃ¡tÃ©,Hungary,NaN,HUN,66.0,89.62,1948,Combine,Male,False,0:00.0,False
4991,21.0,ÃÃ³rir JÃ³nsson,Iceland,NaN,ISL,65.0,89.4,1948,Combine,Male,False,0:00.0,False
712,27.0,Lisa Resch,Germany,NaN,GER,6,88.74,1936,Combine,Women,False,0:00.0,False
4869,25.0,Per Fossum,Norway,NaN,NOR,9.0,88.12,1936,Combine,Male,False,0:00.0,False
782,18.0,Petra Kronberger,Austria,NaN,AUT,11,88.01,1988,Combine,Women,False,0:00.0,False
4870,21.0,"Dick Durrance, Jr.",United States,NaN,USA,10.0,87.74,1936,Combine,Male,False,0:00.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
758,26.0,May Nilsson,Sweden,NaN,SWE,15,13.03,1948,Combine,Women,False,0:00.0,False
5022,28.0,Peter DÃ¼rr,West Germany,NaN,FRG,17.0,123.92,1988,Combine,Male,False,0:00.0,False
829,17.0,Svetlana Novikova,Unified Team,NaN,EUN,19,122.48,1992,Combine,Women,False,0:00.0,False
5021,30.0,Paul Frommelt,Liechtenstein,NaN,LIE,16.0,122.12,1988,Combine,Male,False,0:00.0,False
5086,27.0,Martin Bell,Great Britain,NaN,GBR,25.0,121.83,1992,Combine,Male,False,0:00.0,False
5020,24.0,Bernhard Fahner,Switzerland,NaN,SUI,15.0,120.45,1988,Combine,Male,False,0:00.0,False
757,28.0,Lina Mittner,Switzerland,NaN,SUI,14,12.54,1948,Combine,Women,False,0:00.0,False
4937,31.0,Eberhard Kneisl,Austria,NaN,AUT,11.0,12.36,1948,Combine,Male,False,0:00.0,False
756,28.0,Laila Schou Nilsen,Norway,NaN,NOR,13,12.14,1948,Combine,Women,False,0:00.0,False
4936,27.0,Edy Reinalter,Switzerland,NaN,SUI,10.0,12.01,1948,Combine,Male,False,0:00.0,False
788,19.0,Kristin Krone,United States,NaN,USA,17,114.81,1988,Combine,Women,False,0:00.0,False
5019,23.0,Gregor Hoop,Liechtenstein,NaN,LIE,14.0,114.62,1988,Combine,Male,False,0:00.0,False
5085,19.0,Daniel Vogt,Liechtenstein,NaN,LIE,24.0,112.92,1992,Combine,Male,False,0:00.0,False
787,22.0,Jolanda Kindle,Liechtenstein,NaN,LIE,16,112.72,1988,Combine,Women,False,0:00.0,False
828,18.0,Tetiana Lebedeva,Unified Team,NaN,EUN,18,111.34,1992,Combine,Women,False,0:00.0,False
755,22.0,Resi Hammerer,Austria,NaN,AUT,12,11.87,1948,Combine,Women,False,0:00.0,False
753,21.0,Lucienne Schmidt-Couttet,France,NaN,FRA,10,11.5,1948,Combine,Women,False,0:00.0,False
754,23.0,Suzanne ThiolliÃ¨re,France,NaN,FRA,10,11.5,1948,Combine,Women,False,0:00.0,False
4935,27.0,AntonÃ­n Å ponar,Czechoslovakia,NaN,TCH,9.0,11.19,1948,Combine,Male,False,0:00.0,False
786,23.0,Beth Madsen,United States,NaN,USA,15,108.64,1988,Combine,Women,False,0:00.0,False
5018,22.0,Thomas Stangassinger,Austria,NaN,AUT,13.0,107.87,1988,Combine,Male,False,0:00.0,False
827,16.0,Emma Carrick-Anderson,Great Britain,NaN,GBR,17,107.61,1992,Combine,Women,False,0:00.0,False
785,25.0,Karin Dedler,West Germany,NaN,FRG,14,105.18,1988,Combine,Women,False,0:00.0,False
4993,27.0,GuÃ°mundur GuÃ°mundsson,Iceland,NaN,ISL,67.0,105.11,1948,Combine,Male,False,0:00.0,False
5084,22.0,Ricardo Campo,Spain,NaN,ESP,23.0,104.61,1992,Combine,Male,False,0:00.0,False
784,19.0,Nancy Gee,Canada,NaN,CAN,13,103.86,1988,Combine,Women,False,0:00.0,False
5017,21.0,Christophe PlÃ©,France,NaN,FRA,12.0,103.12,1988,Combine,Male,False,0:00.0,False
5083,22.0,Petar Dichev,Bulgaria,NaN,BUL,22.0,101.59,1992,Combine,Male,False,0:00.0,False
752,28.0,Alexandra NekvapilovÃ¡,Czechoslovakia,NaN,TCH,9,10.98,1948,Combine,Women,False,0:00.0,False
751,24.0,Hedy Schlunegger,Switzerland,NaN,SUI,8,10.2,1948,Combine,Women,False,0:00.0,False

In [26]:
olympic_skiing.to_csv("olympic_skiing.csv")

In [27]:
olympic_skiing_Downhill = olympic_skiing[olympic_skiing["Type"] == "Downhill"]

In [28]:
olympic_skiing_Downhill.to_csv("olympic_skiing_Downhill.csv")

In [29]:
olympic_skiing_Downhill_1= olympic_skiing_Downhill

In [30]:
olympic_skiing_Downhill_1.head()

,Age,Athlete,Country,Medal,NOC,Rank,Time_end,Year,Type,Gender,test,Time_start,test_time
0,22.0,Henri Oreiller,France,Gold,FRA,1,2:55.0,1948,Downhill,Male,False,0:00.0,True
79,25.0,JoÅ¾e Bertoncelj,Yugoslavia,NaN,YUG,80,4:00.2,1948,Downhill,Male,False,0:00.0,True
78,21.0,Leopold SchÃ¤dler,Liechtenstein,NaN,LIE,79,4:00.0,1948,Downhill,Male,False,0:00.0,True
1,26.0,Franz Gabl,Austria,Silver,AUT,2,2:59.1,1948,Downhill,Male,False,0:00.0,True
2,27.0,Karl Molitor,Switzerland,Bronze,SUI,3,3:00.3,1948,Downhill,Male,False,0:00.0,True

In [ ]:
olympic_skiing_Downhill_1

In [31]:
olympic_skiing_Downhill_1["minutes"] = olympic_skiing_Downhill_1["Time_end"].str.split(":", 1, expand = True)[0]
olympic_skiing_Downhill_1["delete"] = olympic_skiing_Downhill_1["Time_end"].str.split(":", 1, expand = True)[1]

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [32]:
olympic_skiing_Downhill_1["seconds"] = olympic_skiing_Downhill_1["delete"].str.split(".", 1, expand = True)[0]
olympic_skiing_Downhill_1["miliseconds"] = olympic_skiing_Downhill_1["delete"].str.split(".", 1, expand = True)[1]

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [33]:
olympic_skiing_Downhill_1["minutes"] = olympic_skiing_Downhill_1["minutes"].astype(int)
olympic_skiing_Downhill_1["seconds"] = olympic_skiing_Downhill_1["seconds"].astype(int)
olympic_skiing_Downhill_1["miliseconds"] = olympic_skiing_Downhill_1["miliseconds"].astype(int)

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [34]:
olympic_skiing_Downhill_1["minutes"] = olympic_skiing_Downhill_1["minutes"] * 60000
olympic_skiing_Downhill_1["seconds"] = olympic_skiing_Downhill_1["seconds"] * 1000

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [35]:
olympic_skiing_Downhill_1["time_miliseconds"] = olympic_skiing_Downhill_1["minutes"] + olympic_skiing_Downhill_1["seconds"] + olympic_skiing_Downhill_1["miliseconds"]

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [39]:
olympic_skiing_Downhill_1.head()

,Age,Athlete,Country,Medal,NOC,Rank,Time_end,Year,Type,Gender,test,Time_start,test_time,minutes,delete,seconds,miliseconds,time_miliseconds
0,22.0,Henri Oreiller,France,Gold,FRA,1,2:55.0,1948,Downhill,Male,False,0:00.0,True,120000,55.0,55000,0,175000
79,25.0,JoÅ¾e Bertoncelj,Yugoslavia,NaN,YUG,80,4:00.2,1948,Downhill,Male,False,0:00.0,True,240000,00.2,0,2,240002
78,21.0,Leopold SchÃ¤dler,Liechtenstein,NaN,LIE,79,4:00.0,1948,Downhill,Male,False,0:00.0,True,240000,00.0,0,0,240000
1,26.0,Franz Gabl,Austria,Silver,AUT,2,2:59.1,1948,Downhill,Male,False,0:00.0,True,120000,59.1,59000,1,179001
2,27.0,Karl Molitor,Switzerland,Bronze,SUI,3,3:00.3,1948,Downhill,Male,False,0:00.0,True,180000,00.3,0,3,180003

In [41]:
olympic_skiing_Downhill_1.sort_values(by = "time_miliseconds", ascending = True)

,Age,Athlete,Country,Medal,NOC,Rank,Time_end,Year,Type,Gender,test,Time_start,test_time,minutes,delete,seconds,miliseconds,time_miliseconds
357,17.0,Michela Figini,Switzerland,Gold,SUI,1,1:13.36,1984,Downhill,Women,False,0:00.0,True,60000,13.36,13000,36,73036
358,20.0,Maria Walliser,Switzerland,Silver,SUI,2,1:13.41,1984,Downhill,Women,False,0:00.0,True,60000,13.41,13000,41,73041
359,21.0,Olga CharvÃ¡tovÃ¡,Czechoslovakia,Bronze,TCH,3,1:13.53,1984,Downhill,Women,False,0:00.0,True,60000,13.53,13000,53,73053
360,22.0,Ariane Ehrat,Switzerland,NaN,SUI,4,1:13.95,1984,Downhill,Women,False,0:00.0,True,60000,13.95,13000,95,73095
361,24.0,Jana GantnerovÃ¡-Å oltÃ½sovÃ¡,Czechoslovakia,NaN,TCH,5,1:14.14,1984,Downhill,Women,False,0:00.0,True,60000,14.14,14000,14,74014
363,25.0,Gerry Sorensen,Canada,NaN,CAN,6,1:14.30,1984,Downhill,Women,False,0:00.0,True,60000,14.30,14000,30,74030
362,19.0,Marina Kiehl,West Germany,NaN,FRG,6,1:14.30,1984,Downhill,Women,False,0:00.0,True,60000,14.30,14000,30,74030
364,25.0,Lea SÃ¶lkner,Austria,NaN,AUT,8,1:14.39,1984,Downhill,Women,False,0:00.0,True,60000,14.39,14000,39,74039
365,20.0,Lisi Kirchler,Austria,NaN,AUT,9,1:14.55,1984,Downhill,Women,False,0:00.0,True,60000,14.55,14000,55,74055
366,17.0,Veronika Wallinger-Stallmaier,Austria,NaN,AUT,10,1:14.76,1984,Downhill,Women,False,0:00.0,True,60000,14.76,14000,76,74076
367,23.0,Laurie Graham,Canada,NaN,CAN,11,1:14.92,1984,Downhill,Women,False,0:00.0,True,60000,14.92,14000,92,74092
368,21.0,Brigitte Oertli,Switzerland,NaN,SUI,12,1:14.93,1984,Downhill,Women,False,0:00.0,True,60000,14.93,14000,93,74093
369,18.0,Sylvia Eder,Austria,NaN,AUT,13,1:14.97,1984,Downhill,Women,False,0:00.0,True,60000,14.97,14000,97,74097
370,23.0,Heidi Wiesler,West Germany,NaN,FRG,14,1:14.98,1984,Downhill,Women,False,0:00.0,True,60000,14.98,14000,98,74098
371,23.0,Caroline Attia,France,NaN,FRA,15,1:15.04,1984,Downhill,Women,False,0:00.0,True,60000,15.04,15000,4,75004
372,26.0,Holly Flanders,United States,NaN,USA,16,1:15.11,1984,Downhill,Women,False,0:00.0,True,60000,15.11,15000,11,75011
373,22.0,Regine MÃ¶senlechner,West Germany,NaN,FRG,17,1:15.16,1984,Downhill,Women,False,0:00.0,True,60000,15.16,15000,16,75016
374,20.0,Liisa Savijarvi,Canada,NaN,CAN,18,1:15.32,1984,Downhill,Women,False,0:00.0,True,60000,15.32,15000,32,75032
375,22.0,Maria Maricich,United States,NaN,USA,19,1:15.55,1984,Downhill,Women,False,0:00.0,True,60000,15.55,15000,55,75055
376,23.0,Marie-Luce Waldmeier,France,NaN,FRA,20,1:15.56,1984,Downhill,Women,False,0:00.0,True,60000,15.56,15000,56,75056
377,20.0,Debbie Armstrong,United States,NaN,USA,21,1:15.57,1984,Downhill,Women,False,0:00.0,True,60000,15.57,15000,57,75057
378,20.0,Karen Stemmle,Canada,NaN,CAN,22,1:15.64,1984,Downhill,Women,False,0:00.0,True,60000,15.64,15000,64,75064
379,26.0,Irene Epple,West Germany,NaN,FRG,23,1:15.65,1984,Downhill,Women,False,0:00.0,True,60000,15.65,15000,65,75065
380,20.0,Ivana ValeÅ¡ovÃ¡,Czechoslovakia,NaN,TCH,24,1:16.43,1984,Downhill,Women,False,0:00.0,True,60000,16.43,16000,43,76043
381,18.0,Jolanda Kindle,Liechtenstein,NaN,LIE,25,1:16.89,1984,Downhill,Women,False,0:00.0,True,60000,16.89,16000,89,76089
382,21.0,Christine Grant,New Zealand,NaN,NZL,26,1:17.52,1984,Downhill,Women,False,0:00.0,True,60000,17.52,17000,52,77052
383,28.0,MichÃ¨le Brigitte Dombard,Belgium,NaN,BEL,27,1:18.92,1984,Downhill,Women,False,0:00.0,True,60000,18.92,18000,92,78092
384,20.0,Marilla Guss,Australia,NaN,AUS,28,1:19.75,1984,Downhill,Women,False,0:00.0,True,60000,19.75,19000,75,79075
385,21.0,Kate Rattray,New Zealand,NaN,NZL,29,1:20.18,1984,Downhill,Women,False,0:00.0,True,60000,20.18,20000,18,80018
386,21.0,Teresa Bustamante,Argentina,NaN,ARG,30,1:21.62,1984,Downhill,Women,False,0:00.0,True,60000,21.62,21000,62,81062
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,27.0,RaÅit Tolun,Turkey,NaN,TUR,87,4:12.1,1948,Downhill,Male,False,0:00.0,True,240000,12.1,12000,1,252001
181,29.0,Bob Arnott,Australia,NaN,AUS,71,4:13.5,1952,Downhill,Male,False,0:00.0,True,240000,13.5,13000,5,253005
230,27.0,Denis Feron,Belgium,NaN,BEL,38,4:16.6,1956,Downhill,Male,False,0:00.0,True,240000,16.6,16000,6,256006
87,23.0,Harry Taylor,Great Britain,NaN,GBR,88,4:17.4,1948,Downhill,Male,False,0:00.0,True,240000,17.4,17000,4,257004
231,NaN,Mahmoud Beiglou,Iran,NaN,IRI,39,4:22.0,1956,Downhill,Male,False,0:00.0,True,240000,22.0,22000,0,262000
232,29.0,Leopold SchÃ¤dler,Liechtenstein,NaN,LIE,40,4:23.7,1956,Downhill,Male,False,0:00.0,True,240000,23.7,23000,7,263007
88,25.0,Thomas de Morawitz,Spain,NaN,ESP,89,4:24.0,1948,Downhill,Male,False,0:00.0,True,240000,24.0,24000,0,264000
89,16.0,Theodor Sele,Liechtenstein,NaN,LIE,90,4:24.1,1948,Downhill,Male,False,0:00.0,True,240000,24.1,24000,1,264001
91,24.0,Ian Appleyard,Great Britain,NaN,GBR,91,4:25.2,1948,Downhill,Male,False,0:00.0,True,240000,25.2,25000,2,265002
90,21.0,Gino de PellegrÃ­n,Argentina,NaN,ARG,91,4:25.2,1948,Downhill,Male,False,0:00.0,True,240000,25.2,25000,2,265002
233,19.0,Vicente Vera,Chile,NaN,CHI,41,4:25.4,1956,Downhill,Male,False,0:00.0,True,240000,25.4,25000,4,265004
234,31.0,Ibrahim Geagea,Lebanon,NaN,LIB,42,4:33.1,1956,Downhill,Male,False,0:00.0,True,240000,33.1,33000,1,273001
406,21.0,Jorge Abelardo Eiras,Argentina,NaN,ARG,76,4:34.51,1964,Downhill,Male,False,0:00.0,True,240000,34.51,34000,51,274051
92,17.0,Pablo Rosenkjer,Argentina,NaN,ARG,93,4:36.2,1948,Downhill,Male,False,0:00.0,True,240000,36.2,36000,2,276002
93,22.0,Dursun Bozkurt,Turkey,NaN,TUR,94,4:37.3,1948,Downhill,Male,False,0:00.0,True,240000,37.3,37000,3,277003
94,27.0,Julio Cernuda,Argentina,NaN,ARG,95,4:46.4,1948,Downhill,Male,False,0:00.0,True,240000,46.4,46000,4,286004
95,21.0,ÃÃ³rir JÃ³nsson,Iceland,NaN,ISL,96,4:47.0,1948,Downhill,Male,False,0:00.0,True,240000,47.0,47000,0,287000
96,18.0,Osman YÃ¼ce,Turkey,NaN,TUR,97,4:49.2,1948,Downhill,Male,False,0:00.0,True,240000,49.2,49000,2,289002
407,20.0,Juan Holz,Chile,NaN,CHI,77,4:51.18,1964,Downhill,Male,False,0:00.0,True,240000,51.18,51000,18,291018
97,27.0,GuÃ°mundur GuÃ°mundsson,Iceland,NaN,ISL,98,4:57.0,1948,Downhill,Male,False,0:00.0,True,240000,57.0,57000,0,297000
235,NaN,Jean Keyrouz,Lebanon,NaN,LIB,43,4:57.6,1956,Downhill,Male,False,0:00.0,True,240000,57.6,57000,6,297006
236,NaN,Benik Amirian,Iran,NaN,IRI,44,5:02.7,1956,Downhill,Male,False,0:00.0,True,300000,02.7,2000,7,302007
98,35.0,"Konstantin, Prince von Padua",Liechtenstein,NaN,LIE,99,5:04.1,1948,Downhill,Male,False,0:00.0,True,300000,04.1,4000,1,304001
99,21.0,JosÃ© VilÃ,Spain,NaN,ESP,100,5:13.0,1948,Downhill,Male,False,0:00.0,True,300000,13.0,13000,0,313000
237,24.0,"Max, Prince von Hohenlohe",Liechtenstein,NaN,LIE,45,5:15.8,1956,Downhill,Male,False,0:00.0,True,300000,15.8,15000,8,315008
100,27.0,Fotis Mavriplis,Greece,NaN,GRE,101,5:39.1,1948,Downhill,Male,False,0:00.0,True,300000,39.1,39000,1,339001
101,20.0,Fernando ArmiÃ±Ã¡n,Spain,NaN,ESP,102,5:41.2,1948,Downhill,Male,False,0:00.0,True,300000,41.2,41000,2,341002
238,39.0,Aris Vatimbellas,Greece,NaN,GRE,46,5:44.2,1956,Downhill,Male,False,0:00.0,True,300000,44.2,44000,2,344002
182,32.0,Alexandros Vouxinos,Greece,NaN,GRE,72,6:10.8,1952,Downhill,Male,False,0:00.0,True,360000,10.8,10000,8,370008
239,29.0,Christos Papageorgiou,Greece,NaN,GRE,47,8:03.2,1956,Downhill,Male,False,0:00.0,True,480000,03.2,3000,2,483002

In [36]:
olympic_skiing_Downhill_1.to_csv("olympic_skiing_Downhill_miliseconds.csv")

In [37]:
s = "4:34.234"
hours, minutes, seconds = (["0", "0"] + s.split(":"))[-3:]
hours = int(hours)
minutes = int(minutes)
seconds = float(seconds)
miliseconds = int(3600000 * hours + 60000 * minutes + 1000 * seconds)