In [2]:
import pandas as pd
%matplotlib inline
import re
import requests as rq
from bs4 import BeautifulSoup

In [128]:
page_list = pd.DataFrame(list(range(1,9)))

In [130]:
page_list.columns = ["pages"]
page_list["pages"] = page_list["pages"].astype(str)

In [99]:
years_list = pd.DataFrame(list(range(1993, 2018)))

In [100]:
years_list.columns = ["years"]
years_list["years"] = years_list["years"].astype(str)

In [161]:
pd.set_option('max_colwidth',100)
pd.set_option('max_rows',100)

In [134]:
urls = "http://www.boxofficemojo.com/yearly/chart/?page=1&view=releasedate&view2=domestic&yr=" + years_list["years"] + "&p=.htm"

In [135]:
urls

0     http://www.boxofficemojo.com/yearly/chart/?page=1&view=releasedate&view2=domestic&yr=1993&p=.htm
1     http://www.boxofficemojo.com/yearly/chart/?page=1&view=releasedate&view2=domestic&yr=1994&p=.htm
2     http://www.boxofficemojo.com/yearly/chart/?page=1&view=releasedate&view2=domestic&yr=1995&p=.htm
3     http://www.boxofficemojo.com/yearly/chart/?page=1&view=releasedate&view2=domestic&yr=1996&p=.htm
4     http://www.boxofficemojo.com/yearly/chart/?page=1&view=releasedate&view2=domestic&yr=1997&p=.htm
5     http://www.boxofficemojo.com/yearly/chart/?page=1&view=releasedate&view2=domestic&yr=1998&p=.htm
6     http://www.boxofficemojo.com/yearly/chart/?page=1&view=releasedate&view2=domestic&yr=1999&p=.htm
7     http://www.boxofficemojo.com/yearly/chart/?page=1&view=releasedate&view2=domestic&yr=2000&p=.htm
8     http://www.boxofficemojo.com/yearly/chart/?page=1&view=releasedate&view2=domestic&yr=2001&p=.htm
9     http://www.boxofficemojo.com/yearly/chart/?page=1&view=releasedate&view2=domestic&yr=2002&p=.htm
10    http://www.boxofficemojo.com/yearly/chart/?page=1&view=releasedate&view2=domestic&yr=2003&p=.htm
11    http://www.boxofficemojo.com/yearly/chart/?page=1&view=releasedate&view2=domestic&yr=2004&p=.htm
12    http://www.boxofficemojo.com/yearly/chart/?page=1&view=releasedate&view2=domestic&yr=2005&p=.htm
13    http://www.boxofficemojo.com/yearly/chart/?page=1&view=releasedate&view2=domestic&yr=2006&p=.htm
14    http://www.boxofficemojo.com/yearly/chart/?page=1&view=releasedate&view2=domestic&yr=2007&p=.htm
15    http://www.boxofficemojo.com/yearly/chart/?page=1&view=releasedate&view2=domestic&yr=2008&p=.htm
16    http://www.boxofficemojo.com/yearly/chart/?page=1&view=releasedate&view2=domestic&yr=2009&p=.htm
17    http://www.boxofficemojo.com/yearly/chart/?page=1&view=releasedate&view2=domestic&yr=2010&p=.htm
18    http://www.boxofficemojo.com/yearly/chart/?page=1&view=releasedate&view2=domestic&yr=2011&p=.htm
19    http://www.boxofficemojo.com/yearly/chart/?page=1&view=releasedate&view2=domestic&yr=2012&p=.htm
20    http://www.boxofficemojo.com/yearly/chart/?page=1&view=releasedate&view2=domestic&yr=2013&p=.htm
21    http://www.boxofficemojo.com/yearly/chart/?page=1&view=releasedate&view2=domestic&yr=2014&p=.htm
22    http://www.boxofficemojo.com/yearly/chart/?page=1&view=releasedate&view2=domestic&yr=2015&p=.htm
23    http://www.boxofficemojo.com/yearly/chart/?page=1&view=releasedate&view2=domestic&yr=2016&p=.htm
24    http://www.boxofficemojo.com/yearly/chart/?page=1&view=releasedate&view2=domestic&yr=2017&p=.htm
Name: years, dtype: object

In [3]:
url = "http://www.boxofficemojo.com/yearly/chart/?page=1&view=releasedate&view2=domestic&yr=2017&p=.htm"
response = rq.post(url)
doc = BeautifulSoup(response.text, "html.parser")

In [119]:
movie_budget_list = []
for i in doc.find_all("tr")[9:109]:
    dictionary = {}
    dictionary["Rank"] = i.find_all("td")[0].text.strip()
    dictionary["Name"] = i.find_all("td")[1].text.strip()
    dictionary["Studio"] = i.find_all("td")[2].text.strip()
    dictionary["Total Gross"] = i.find_all("td")[3].text.strip()
    dictionary["Opening"] = i.find_all("td")[5].text.strip()
    dictionary["Open_date"] = i.find_all("td")[7].text.strip()
    dictionary["end_date"] = i.find_all("td")[8].text.strip()
    dictionary["Years"] = 2017
    print(i.find_all("td")[3].text.strip())
    movie_budget_list.append(dictionary)

$504,014,165
$412,563,408
$397,271,356
$389,813,101
$334,201,140
$327,481,748
$309,444,758
$264,624,300
$226,277,068
$225,764,765
$223,173,455
$188,045,546
$175,750,384
$175,484,140
$175,003,033
$172,558,876
$168,052,812
$163,504,128
$152,901,115
$146,880,162
$138,141,585
$130,168,683
$115,534,750
$115,108,515
$114,434,010
$107,825,862
$102,092,201
$100,199,005
$99,471,983
$99,375,556
$92,029,184
$91,524,557
$86,089,513
$85,364,450
$80,101,125
$75,468,583
$74,262,031
$73,921,000
$71,358,592
$68,755,967
$64,321,890
$59,281,555
$58,060,186
$57,386,418
$55,683,845
$51,573,925
$51,342,000
$50,701,325
$47,319,572
$45,852,178
$45,157,105
$45,020,282
$45,018,541
$44,922,302
$44,898,413
$44,307,192
$42,873,127
$41,189,488
$40,563,557
$39,175,066
$38,646,925
$38,052,832
$36,249,674
$34,393,507
$34,121,140
$33,800,859
$33,424,531
$33,370,166
$32,187,017
$32,149,404
$30,718,107
$30,353,973
$30,348,555
$30,234,022
$29,157,884
$28,370,522
$28,306,445
$27,793,018
$27,780,977
$27,020,284
$26,830,068
$25,601,000
$25,584,504
$24,801,212
$22,940,619
$22,395,806
$22,196,285
$22,105,643
$21,885,107
$21,858,070
$20,783,704
$20,738,724
$20,497,844
$20,186,659
$18,600,152
$18,598,731
$18,062,909
$17,800,004
$17,445,186
$17,273,059

In [120]:
df_movie_budget = pd.DataFrame(movie_budget_list)
df_movie_budget.head()

,Name,Open_date,Opening,Rank,Studio,Total Gross,Years,end_date
0,Beauty and the Beast (2017),3/17,"$174,750,616",1,BV,"$504,014,165",2017,7/13
1,Wonder Woman,6/2,"$103,251,471",2,WB,"$412,563,408",2017,11/9
2,Star Wars: The Last Jedi,12/15,"$220,009,584",3,BV,"$397,271,356",2017,-
3,Guardians of the Galaxy Vol. 2,5/5,"$146,510,104",4,BV,"$389,813,101",2017,9/21
4,Spider-Man: Homecoming,7/7,"$117,027,503",5,Sony,"$334,201,140",2017,11/30

In [124]:
movie_budget_years = []

for i in urls:
    response = rq.post(i)
    doc = BeautifulSoup(response.text, "html.parser")
    for rows in doc.find_all("tr")[9:109]:
        dictionary = {}
        dictionary["Rank"] = rows.find_all("td")[0].text.strip()
        dictionary["Name"] = rows.find_all("td")[1].text.strip()
        dictionary["Studio"] = rows.find_all("td")[2].text.strip()
        dictionary["Total Gross"] = rows.find_all("td")[3].text.strip()
        dictionary["Opening"] = rows.find_all("td")[5].text.strip()
        dictionary["Years"] = 2017 
#         print(i.find_all("td")[3].text.strip())
        movie_budget_years.append(dictionary)

In [125]:
df_movie_budget_years = pd.DataFrame(movie_budget_years)
df_movie_budget_years.head()

                   Name      Opening Rank Studio   Total Gross  Years
0         Jurassic Park  $47,026,828    1   Uni.  $357,067,947   2017
1        Mrs. Doubtfire  $20,468,847    2    Fox  $219,195,243   2017
2          The Fugitive  $23,758,855    3     WB  $183,875,760   2017
3              The Firm  $25,400,000    4   Par.  $158,348,367   2017
4  Sleepless in Seattle  $17,253,733    5   TriS  $126,680,884   2017

In [137]:
df_movie_budget_years.tail()

                      Name     Opening Rank Studio  Total Gross  Years
2495  The Greatest Showman  $8,800,000   96    Fox  $18,598,731   2017
2496        Only The Brave  $6,002,665   97   Sony  $18,062,909   2017
2497               mother!  $7,534,673   98   Par.  $17,800,004   2017
2498  The Zookeeper's Wife  $3,288,835   99  Focus  $17,445,186   2017
2499      The Glass Castle  $4,678,548  100    LGF  $17,273,059   2017

In [138]:
urls = "http://www.boxofficemojo.com/yearly/chart/?page=2&view=releasedate&view2=domestic&yr=" + years_list["years"] + "&p=.htm"

In [139]:
movie_budget_page_2 = []

for i in urls:
    response = rq.post(i)
    doc = BeautifulSoup(response.text, "html.parser")
    for rows in doc.find_all("tr")[9:109]:
        dictionary = {}
        dictionary["Rank"] = rows.find_all("td")[0].text.strip()
        dictionary["Name"] = rows.find_all("td")[1].text.strip()
        dictionary["Studio"] = rows.find_all("td")[2].text.strip()
        dictionary["Total Gross"] = rows.find_all("td")[3].text.strip()
        dictionary["Opening"] = rows.find_all("td")[5].text.strip()
        dictionary["Years"] = 2017 
#         print(i.find_all("td")[3].text.strip())
        movie_budget_page_2.append(dictionary)

In [140]:
df_movie_budget_page_2 = pd.DataFrame(movie_budget_page_2)
df_movie_budget_page_2.head()

                       Name     Opening Rank Studio  Total Gross  Years
0          Army of Darkness  $4,424,535  101   Uni.  $11,502,976   2017
1  Manhattan Murder Mystery  $2,015,360  102   TriS  $11,330,911   2017
2            Who's the Man?  $4,533,392  103     NL  $11,299,730   2017
3         For Love or Money  $4,016,220  104   Uni.  $11,146,270   2017
4         Mad Dog and Glory  $3,815,555  105   Uni.  $11,081,586   2017

In [141]:
urls = "http://www.boxofficemojo.com/yearly/chart/?page=3&view=releasedate&view2=domestic&yr=" + years_list["years"] + "&p=.htm"

In [157]:
movie_budget_page_3 = []

for i in urls:
    response = rq.post(i)
    doc = BeautifulSoup(response.text, "html.parser")
#     for rows in doc.find_all("tr")[9:67]:
    for rows in doc.find_all("tr")[9:109]:
        try:
            dictionary = {}
            dictionary["Rank"] = rows.find_all("td")[0].text.strip()
            dictionary["Name"] = rows.find_all("td")[1].text.strip()
            dictionary["Studio"] = rows.find_all("td")[2].text.strip()
            dictionary["Total Gross"] = rows.find_all("td")[3].text.strip()
            dictionary["Opening"] = rows.find_all("td")[5].text.strip()
            dictionary["Years"] = 2017 
#             print(rows.find_all("td")[0].text.strip())
            movie_budget_page_3.append(dictionary)
        except:
            print("Failed")
            pass

Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed

In [162]:
df_movie_budget_page_3 = pd.DataFrame(movie_budget_page_3)
df_movie_budget_page_3.head(100)

,Name,Opening,Rank,Studio,Total Gross,Years
0,Street Knight,N/A,201,Can.,"$841,015",2017
1,The Last Days of Chez Nous,N/A,202,FL,"$831,578",2017
2,"Faraway, So Close!","$55,019",203,SPC,"$810,455",2017
3,Visions of Light,"$27,761",204,Kino,"$799,856",2017
4,The Accompanist,N/A,205,SPC,"$769,983",2017
5,"Bodies, Rest and Motion","$75,957",206,NL,"$764,724",2017
6,Household Saints,N/A,207,FL,"$712,418",2017
7,The Opposite Sex and How to Live With Them,"$525,004",208,Mira.,"$690,966",2017
8,Leolo,N/A,209,FL,"$611,703",2017
9,Deception (1993),"$162,274",210,Mira.,"$608,866",2017
10,Road Scholar,"$8,635",211,Gold.,"$597,564",2017
11,The Ballad of Little Jo,"$20,773",212,FL,"$543,091",2017
12,Sex Is...,N/A,213,OutF,"$530,833",2017
13,Just Another Girl on the IRT,N/A,214,Mira.,"$479,169",2017
14,Especially on Sunday,"$51,479",215,Mira.,"$442,676",2017
15,American Heart,"$5,549",216,Trit,"$384,048",2017
16,House of Cards,"$12,753",217,Mira.,"$322,871",2017
17,The Music of Chance,"$13,359",218,IRS,"$313,967",2017
18,Ethan Frome,"$57,623",219,Mira.,"$296,081",2017
19,Riff-Raff,N/A,220,FL,"$295,444",2017
20,Equinox,"$6,310",221,IRS,"$279,627",2017
21,Wrestling Ernest Hemingway,"$14,871",222,WB,"$278,720",2017
22,Tokyo Decadence,N/A,223,N.Arts,"$277,845",2017
23,Amongst Friends,N/A,224,FL,"$265,000",2017
24,Dead Alive,"$23,765",225,Trim.,"$242,623",2017
25,The Abyss Special Edition,"$20,962",226,Fox,"$238,737",2017
26,Fifty/Fifty,N/A,227,Can.,"$229,041",2017
27,Bopha!,"$88,390",228,Par.,"$212,483",2017
28,Man Bites Dog,"$15,176",229,Roxie,"$205,569",2017
29,Romper Stomper,"$8,233",230,AcdE,"$175,340",2017
30,No Place to Hide,"$91,000",231,Can.,"$135,004",2017
31,The Saint of Fort Washington,"$19,409",232,WB,"$134,454",2017
32,The Trial,"$14,854",233,Angk,"$119,267",2017
33,Bank Robber,"$34,998",234,IRS,"$115,842",2017
34,Guncrazy,"$6,640",235,MRa,"$114,516",2017
35,Crush (1993),"$12,205",236,Strand,"$107,792",2017
36,Twenty Bucks,"$30,667",237,Trit,"$89,558",2017
37,It's All True,N/A,238,Par.,"$86,980",2017
38,Wilder Napalm,"$12,078",239,TriS,"$84,859",2017
39,The Pickle,"$45,570",240,Col.,"$84,471",2017
40,Volere Volare,"$7,572",241,FL,"$78,144",2017
41,Betty,"$5,243",242,MK2,"$58,099",2017
42,Return of the Living Dead III,"$14,810",243,Trim.,"$54,207",2017
43,Mac,"$27,587",244,Gold.,"$39,437",2017
44,Twist (1993),"$1,589",245,Trit,"$36,875",2017
45,Freaked,"$6,957",246,Fox,"$29,296",2017
46,Morning Glory (1993),N/A,247,AcdE,"$28,409",2017
47,Wild West,N/A,248,Gold.,"$24,079",2017
48,Dangerous Game,"$16,995",249,MGM,"$23,671",2017
49,American Friends,"$5,334",250,Castle,"$23,034",2017
50,That Night,N/A,251,WB,"$20,194",2017
51,Deadfall,"$9,183",252,Trim.,"$18,369",2017
52,The Last Party,"$4,088",253,Trit,"$11,156",2017
53,Motorama,"$5,577",254,2Mn,"$10,535",2017
54,The Hawk,"$4,535",255,Castle,"$8,906",2017
55,By the Sword,"$4,078",256,Hns.,"$6,220",2017
56,When the Party's Over,"$2,531",257,Strand,"$3,514",2017
57,The Philadelphia Experiment II,N/A,258,Trim.,"$2,970",2017
58,Children of Fate,"$1,099",259,FRun,"$1,738",2017
59,"$4,985,441,134",-,Totals:,-,-,2017
60,"$19,248,807",-,Averages:,-,-,2017
61,Where the Rivers Flow North,"$46,775",201,Cale.,"$595,505",2017
62,Tom and Viv,"$21,968",202,Mira.,"$538,534",2017
63,Federal Hill,"$20,601",203,Trim.,"$514,775",2017
64,The Browning Version,"$48,719",204,Par.,"$487,391",2017
65,Colonel Chabert,"$19,101",205,Oct.,"$464,284",2017
66,"The Wonderful, Horrible Life of Leni Riefenstahl","$9,711",206,Kino,"$449,707",2017
67,Body Snatchers,"$31,494",207,WB,"$428,868",2017
68,Killing Zoe,"$30,586",208,Oct.,"$418,961",2017
69,Golden Gate,"$258,040",209,Gold.,"$395,105",2017
70,Nostradamus,"$27,312",210,OrionC,"$364,164",2017
71,The Cement Garden,"$23,410",211,Oct.,"$322,975",2017
72,Trading Mom,"$68,570",212,Trim.,"$319,123",2017
73,The Slingshot,"$9,711",213,SPC,"$308,368",2017
74,Rapa Nui,N/A,214,WB,"$305,070",2017
75,Bulletproof Heart,"$3,406",215,Key.,"$297,415",2017
76,That's Entertainment! III,"$36,220",216,MGM,"$280,163",2017
77,Dr. Strangelove (Re-issue),"$11,751",217,SRep,"$275,902",2017
78,Cafe au Lait,N/A,218,NYer,"$274,596",2017
79,Dream Lover,"$44,701",219,Gram.,"$256,264",2017
80,The New Age,N/A,220,WB,"$245,217",2017
81,Fear of a Black Hat,"$15,191",221,IDP,"$233,824",2017
82,Zero Patience,N/A,222,Strand,"$217,300",2017
83,Sleep with Me,"$33,004",223,MGM,"$200,151",2017
84,My Life's in Turnaround,N/A,224,Arro.,"$163,383",2017
85,Ladybird Ladybird,N/A,225,Gold.,"$152,457",2017
86,La Scorta,"$6,998",226,First,"$147,107",2017
87,Police Academy 7: Mission to Moscow,N/A,227,WB,"$126,247",2017
88,Oleanna,"$25,316",228,Gold.,"$124,693",2017
89,There Goes My Baby,N/A,229,Orion,"$123,509",2017
90,Suture,N/A,230,Gold.,"$102,780",2017
91,Totally F---ed Up,N/A,231,Strand,"$101,071",2017
92,A Place in the World,"$9,970",232,First,"$99,707",2017
93,In Custody,"$7,701",233,SPC,"$92,612",2017
94,Imaginary Crimes,"$21,748",234,WB,"$89,611",2017
95,Raining Stones,N/A,235,N.Arts,"$89,388",2017
96,Second Best,"$19,190",236,WB,"$86,115",2017
97,"The Beans of Egypt, Maine","$5,263",237,IRS,"$73,956",2017
98,A Troll in Central Park,N/A,238,WB,"$71,368",2017
99,Freedom on My Mind,"$4,272",239,Tara,"$71,176",2017

In [159]:
df_movie_budget_page_3.tail()

,Name,Opening,Rank,Studio,Total Gross,Years
2398,Long Strange Trip - The Untold Story of The Grateful Dead,"$33,272",296,Abr.,"$351,957",2017
2399,Pearl Jam - Let's Play Two,"$53,177",297,Abr.,"$348,833",2017
2400,Canelo vs. Chavez Jr.,"$343,387",298,Fathom,"$343,387",2017
2401,This Is Not What I Expected,"$135,252",299,WGUSA,"$337,670",2017
2402,Dunkirk (Re-Issue 12/1),"$122,115",300,WB,"$327,615",2017

In [164]:
urls = "http://www.boxofficemojo.com/yearly/chart/?page=4&view=releasedate&view2=domestic&yr=" + years_list["years"] + "&p=.htm"

In [165]:
movie_budget_page_4 = []

for i in urls:
    response = rq.post(i)
    doc = BeautifulSoup(response.text, "html.parser")
#     for rows in doc.find_all("tr")[9:67]:
    for rows in doc.find_all("tr")[9:109]:
        try:
            dictionary = {}
            dictionary["Rank"] = rows.find_all("td")[0].text.strip()
            dictionary["Name"] = rows.find_all("td")[1].text.strip()
            dictionary["Studio"] = rows.find_all("td")[2].text.strip()
            dictionary["Total Gross"] = rows.find_all("td")[3].text.strip()
            dictionary["Opening"] = rows.find_all("td")[5].text.strip()
            dictionary["Years"] = 2017 
#             print(rows.find_all("td")[0].text.strip())
            movie_budget_page_4.append(dictionary)
        except:
            print("Failed")
            pass

Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed

In [166]:
df_movie_budget_page_4 = pd.DataFrame(movie_budget_page_4)
df_movie_budget_page_4.head(100)

,Name,Opening,Rank,Studio,Total Gross,Years
0,Tarantella,"$1,403",301,Tara,"$6,235",2017
1,Not Bad for a Girl,N/A,302,Hor.,"$6,152",2017
2,Blue Juice,"$2,750",303,Filmo,"$4,535",2017
3,Bird of Prey,N/A,304,N.Arts,"$3,652",2017
4,Tell the Truth and Run: George Seldes and the American Press,N/A,305,Glds.,"$3,204",2017
5,Shopping,"$1,983",306,Conc,"$3,061",2017
6,The Shot,N/A,307,BW,"$2,970",2017
7,Mercy,N/A,308,Una.,"$2,967",2017
8,I Shot a Man in Vegas,N/A,309,Arro.,"$2,684",2017
9,Eden Valley,N/A,310,MD,"$2,642",2017
10,American Strays,"$1,183",311,Una.,"$1,910",2017
11,"$5,706,784,971",-,Totals:,-,-,2017
12,"$18,349,791",-,Averages:,-,-,2017
13,Childhood's End,"$2,556",301,Plainv.,"$3,804",2017
14,Beyond Barbed Wire,"$1,668",302,M&A,"$3,109",2017
15,Trojan War,$217,303,WB,$309,2017
16,"$6,671,782,536",-,Totals:,-,-,2017
17,"$22,019,084",-,Averages:,-,-,2017
18,Mean Streets (Re-issue),"$32,645",301,WB,"$32,645",2017
19,Bad Manners,"$11,656",302,Pha.,"$31,687",2017
20,Carla's Song,N/A,303,Shad.,"$25,845",2017
21,Go Now!,"$3,657",304,Gram.,"$25,695",2017
22,Dream for an Insomniac,"$6,201",305,Lions,"$24,727",2017
23,Chicago Cab,"$2,947",306,Castle,"$23,946",2017
24,The Last Big Thing,N/A,307,Strat.,"$22,731",2017
25,Off the Menu...,N/A,308,N.Arts,"$19,285",2017
26,Talk of Angels,"$6,876",309,Mira.,"$18,281",2017
27,The Leading Man,"$2,483",310,N.Arts,"$18,012",2017
28,Dear Jesse,"$1,508",311,Cow.,"$17,744",2017
29,"Comrades, Almost a Love Story","$8,510",312,Rim,"$17,676",2017
30,Ten Benny,N/A,313,AL,"$15,843",2017
31,Esmeralda Comes by Night,N/A,314,FL,"$15,671",2017
32,Full-Tilt Boogie,"$9,895",315,Mira.,"$15,313",2017
33,The Break,"$5,975",316,Castle,"$14,760",2017
34,Hard Core Logo,"$3,864",317,Cow.,"$14,540",2017
35,Savior,"$3,898",318,Lions,"$14,328",2017
36,Little Boy Blue,N/A,319,Castle,"$12,958",2017
37,Hit Me,"$3,348",320,Castle,"$12,500",2017
38,Storefront Hitchcock,"$1,803",321,Mira.,"$12,355",2017
39,True Friends,N/A,322,2Gen,"$12,231",2017
40,The Last Broadcast,N/A,323,Wvl.,"$12,097",2017
41,Stolen Moments,"$3,636",324,FRun,"$9,743",2017
42,Out of the Past (1998),"$1,671",325,Zeit.,"$9,078",2017
43,Hi-Life,"$3,773",326,Lions,"$9,066",2017
44,Ill Gotten Gains,"$4,401",327,Spat,"$8,329",2017
45,The Last of the High Kings,"$5,569",328,Mira.,"$7,682",2017
46,The Jew in the Lotus,N/A,329,Blin,"$6,940",2017
47,Blood of His Own,N/A,330,Toz.,"$6,792",2017
48,Reach the Rock,"$3,317",331,Gram.,"$4,960",2017
49,The Other Side of Sunday,"$2,621",332,First,"$4,769",2017
50,Eden (1998),"$1,564",333,Leg.,"$4,210",2017
51,Detroit 9000 (Re-issue),"$2,054",334,Roll.,"$3,179",2017
52,Thursday,"$1,971",335,Leg.,"$3,121",2017
53,"Pretty Village, Pretty Flame",$141,336,Wells,$211,2017
54,"$6,574,789,117",-,Totals:,-,-,2017
55,"$19,567,825",-,Averages:,-,-,2017
56,Among Giants,"$13,276",301,FoxS,"$65,748",2017
57,Joe the King,"$11,793",302,Trim.,"$60,279",2017
58,Shiloh 2: Shiloh Season,"$2,765",303,Leg.,"$58,946",2017
59,"God Said, 'Ha!'","$12,022",304,Mira.,"$55,970",2017
60,Six Ways to Sunday,"$9,521",305,Strat.,"$54,751",2017
61,The Grandfather,"$12,726",306,Mira.,"$54,468",2017
62,Southie,"$16,860",307,Lions,"$52,819",2017
63,Sirf Tum,"$50,785",308,Eros,"$50,785",2017
64,Following,"$3,668",309,Zeit.,"$48,482",2017
65,International Khiladi,"$47,238",310,Eros,"$47,238",2017
66,On the Ropes,"$7,431",311,Wells,"$46,737",2017
67,Get Bruce!,"$19,736",312,Mira.,"$44,337",2017
68,Regret to Inform,"$6,294",313,AL,"$44,204",2017
69,Miss Julie,N/A,314,UA,"$43,941",2017
70,Dahek,"$41,284",315,Eros,"$41,284",2017
71,B. Monkey,"$17,436",316,Mira.,"$39,371",2017
72,Whiteboyz,"$23,149",317,FoxS,"$38,738",2017
73,Man of the Century,"$7,724",318,FL,"$34,857",2017
74,Friends and Lovers,"$33,543",319,Lions,"$33,543",2017
75,Beyond the Clouds,"$12,596",320,Sce.,"$31,738",2017
76,Free Enterprise,"$13,086",321,Reg.,"$30,229",2017
77,The Lovers on the Bridge,"$21,482",322,Mira.,"$29,679",2017
78,Beyond Beautiful,"$29,480",323,Cow.,"$29,480",2017
79,Best Laid Plans,"$14,872",324,FoxS,"$27,816",2017
80,Finding North,"$5,952",325,Cow.,"$27,466",2017
81,The Joyriders,"$26,999",326,Prov.,"$26,999",2017
82,Metroland,"$26,682",327,Lions,"$26,682",2017
83,All the Little Animals,N/A,328,Lions,"$26,558",2017
84,The Monster (Re-issue),"$5,793",329,Lions,"$22,819",2017
85,Frogs for Snakes,"$12,191",330,Art.,"$21,589",2017
86,New Rose Hotel,"$5,147",331,Lions,"$21,521",2017
87,Clubland (1999),"$12,598",332,Leg.,"$18,529",2017
88,Molly,"$9,683",333,MGM,"$17,650",2017
89,Mighty Peking Man (Re-issue),"$4,873",334,Cow.,"$17,368",2017
90,2by4,"$8,163",335,Strand,"$17,162",2017
91,Spanish Fly,N/A,336,Mira.,"$15,503",2017
92,The Apple,"$15,207",337,NYer,"$15,207",2017
93,"Blood, Guts, Bullets & Octane","$7,560",338,Lions,"$15,035",2017
94,Dry Cleaning,"$14,919",339,Strand,"$14,919",2017
95,La Cucaracha,"$14,692",340,Wht.,"$14,692",2017
96,I'm Losing You,"$7,027",341,Strand,"$13,996",2017
97,The Winners,"$4,293",342,First,"$13,066",2017
98,Dial 'M' for Murder (Re-issue),"$12,562",343,WB,"$12,562",2017
99,Dreaming of Joseph Lees,"$7,680",344,FoxS,"$12,044",2017

In [167]:
urls = "http://www.boxofficemojo.com/yearly/chart/?page=5&view=releasedate&view2=domestic&yr=" + years_list["years"] + "&p=.htm"

In [168]:
movie_budget_page_5 = []

for i in urls:
    response = rq.post(i)
    doc = BeautifulSoup(response.text, "html.parser")
#     for rows in doc.find_all("tr")[9:67]:
    for rows in doc.find_all("tr")[9:109]:
        try:
            dictionary = {}
            dictionary["Rank"] = rows.find_all("td")[0].text.strip()
            dictionary["Name"] = rows.find_all("td")[1].text.strip()
            dictionary["Studio"] = rows.find_all("td")[2].text.strip()
            dictionary["Total Gross"] = rows.find_all("td")[3].text.strip()
            dictionary["Opening"] = rows.find_all("td")[5].text.strip()
            dictionary["Years"] = 2017 
#             print(rows.find_all("td")[0].text.strip())
            movie_budget_page_5.append(dictionary)
        except:
            print("Failed")
            pass

Failed
Failed
Failed
Failed
Failed
Failed

In [169]:
df_movie_budget_page_5 = pd.DataFrame(movie_budget_page_5)
df_movie_budget_page_5.head(100)

,Name,Opening,Rank,Studio,Total Gross,Years
0,Gangster No. 1,"$5,514",401,IFC,"$30,915",2017
1,Sonny,"$17,639",402,GldC,"$30,005",2017
2,Teddy Bears' Picnic,N/A,403,Magn.,"$28,149",2017
3,"Massoud, the Afghan","$5,859",404,NYer,"$26,747",2017
4,All About Lily Chou-Chou,"$3,064",405,Cow.,"$26,485",2017
5,Safe Conduct,"$6,811",406,Emp.,"$25,440",2017
6,Liars Club,"$13,623",407,Odys,"$23,792",2017
7,All the Queen's Men,"$15,026",408,Strand,"$23,662",2017
8,Blackboards,"$3,416",409,Leis.,"$23,520",2017
9,Esther Kahn,"$5,124",410,Emp.,"$23,371",2017
10,Cuba Feliz,"$6,369",411,Emp.,"$22,071",2017
11,Master Flying Guillotine (re-issue),"$6,836",412,Path.,"$21,779",2017
12,Crazy as Hell,"$13,341",413,AL,"$21,679",2017
13,Hush!,"$5,322",414,Strand,"$21,278",2017
14,The Isle,"$4,546",415,Emp.,"$20,666",2017
15,Devils on the Doorstep,"$3,227",416,Cow.,"$18,944",2017
16,Love and a Bullet,"$9,994",417,SGem,"$18,926",2017
17,Quitting,"$7,908",418,SPC,"$18,531",2017
18,Hell House,"$6,950",419,7Art,"$18,279",2017
19,Scarlet Diva,"$4,547",420,MB,"$18,062",2017
20,Night at the Golden Eagle,"$7,380",421,Key.,"$17,643",2017
21,The Days of Nick Drake,"$4,684",422,Roxie,"$17,384",2017
22,Vulgar,"$9,377",423,Lions,"$15,927",2017
23,Bobby G. Can't Swim,"$4,433",424,Gabri.,"$15,900",2017
24,Last Dance (2002),"$3,477",425,FRun,"$15,515",2017
25,Pipe Dream,"$7,998",426,Castle,"$15,430",2017
26,The Next Big Thing,N/A,427,Castle,"$14,600",2017
27,The Settlers,"$2,812",428,FRun,"$14,556",2017
28,Lansdown,"$4,323",429,Outr.,"$12,614",2017
29,Shaye & Kiki,N/A,430,Indic.,"$12,000",2017
30,Yellow Asphalt,$489,431,NYer,"$11,907",2017
31,Smokers Only,"$3,102",432,Strand,"$11,871",2017
32,Janice Beard,"$4,248",433,Emp.,"$11,816",2017
33,Crop Circles: Quest for Truth,"$5,763",434,Open,"$11,562",2017
34,The Mesmerist,"$11,422",435,7Art,"$11,422",2017
35,Family Fundamentals,"$7,352",436,Focus,"$11,344",2017
36,Love in the Time of Money,"$6,040",437,Think,"$10,410",2017
37,Revolution #9,"$4,936",438,Exil.,"$10,133",2017
38,Take Care of My Cat,"$3,137",439,Kino,"$9,866",2017
39,Il Posto,"$2,581",440,Cow.,"$9,080",2017
40,ABC Africa,$559,441,NYer,"$9,075",2017
41,The Rising Place,"$7,565",442,Flat,"$8,360",2017
42,The Dogwalker (2002),"$4,726",443,Outr.,"$7,420",2017
43,Group,"$2,260",444,AL,"$7,281",2017
44,Buddha Heads,"$6,739",445,Path.,"$6,739",2017
45,All My Loved Ones,"$3,222",446,N.Arts,"$6,237",2017
46,The Phantom of Liberte (Re-issue),"$6,172",447,Rialto,"$6,172",2017
47,Ted Bundy,"$1,710",448,Tar.,"$6,073",2017
48,The First $20 Million...,"$2,535",449,Fox,"$5,491",2017
49,Perfect Pie,"$5,000",450,OFI,"$5,000",2017
50,Secret Society,$933,451,FRun,"$4,725",2017
51,"Sia, The Dream of the Python","$3,313",452,Artma,"$4,662",2017
52,My Kingdom,"$2,607",453,First,"$4,296",2017
53,Hera Purple,"$1,926",454,Path.,"$4,123",2017
54,Caravaggio (Re-issue),$532,455,Zeit.,"$3,774",2017
55,Revolution OS,"$3,500",456,7Art,"$3,500",2017
56,Looking Through Lillian,"$1,707",457,Path.,"$3,300",2017
57,A Cuban Legend,"$2,590",458,Wan.,"$3,212",2017
58,Tattoo Bar,"$1,812",459,Artma,"$2,964",2017
59,Ash Wednesday,"$2,942",460,Emp.,"$2,942",2017
60,Dead or Alive: Final,"$1,841",461,Kino,"$2,591",2017
61,Standing by Yourself,"$2,200",462,Cheap,"$2,500",2017
62,ZigZag,"$1,649",463,Silv.,"$2,418",2017
63,Virgil Bliss,$205,464,FRun,"$2,219",2017
64,The 4th Tenor,"$2,152",465,Wine,"$2,152",2017
65,Stripped,"$2,151",466,Dyl.,"$2,151",2017
66,Stealing the Fire,"$1,053",467,Frie.,"$2,139",2017
67,Some Body,"$2,042",468,Lot47,"$2,042",2017
68,Choice of Weapons,"$2,032",469,Outr.,"$2,032",2017
69,Mr. Smith Gets a Hustler,"$1,583",470,Outr.,"$1,915",2017
70,By Hook or by Crook,"$1,802",471,AL,"$1,802",2017
71,The Opera Lover,"$1,167",472,Outr.,"$1,798",2017
72,Mama Africa,"$1,581",473,Wells,"$1,581",2017
73,Blackwoods,"$1,500",474,Boll,"$1,500",2017
74,Heartbreak Hospital,"$1,480",475,7Art,"$1,480",2017
75,Execution of Wanda Jean,"$1,386",476,7Art,"$1,386",2017
76,Besotted,$656,477,AL,"$1,379",2017
77,The Jimmy Show,$703,478,First,"$1,000",2017
78,Lonely Affair of the Heart,$932,479,Path.,$932,2017
79,'R Xmas,$850,480,Path.,$850,2017
80,"$9,206,357,935",-,Totals:,-,-,2017
81,"$19,179,912",-,Averages:,-,-,2017
82,Girlhood,"$4,845",401,Wells,"$37,977",2017
83,Bollywood/Hollywood (USA),"$5,470",402,Magn.,"$37,962",2017
84,Millennium Actress,"$18,732",403,GF,"$37,641",2017
85,This Thing of Ours,"$8,007",404,SmlP,"$37,227",2017
86,Out of Control,"$36,486",405,Raj.,"$36,486",2017
87,From Here to Eternity (50th Anniversary),"$18,176",406,SRep,"$36,416",2017
88,The Event,"$19,206",407,Think,"$35,554",2017
89,A Decade Under the Influence,"$2,320",408,IFC,"$34,837",2017
90,Martin and Orloff,"$6,988",409,Spit,"$34,222",2017
91,Bolivia,"$9,899",410,CTr,"$33,098",2017
92,Fanfan la Tulipe,"$32,686",411,Chri.,"$32,686",2017
93,Garage Days,"$20,600",412,FoxS,"$32,500",2017
94,Porn Theatre,"$3,367",413,Strand,"$31,653",2017
95,In My Skin,"$7,572",414,Wells,"$31,046",2017
96,Sans Soleil (Re-issue),"$6,460",415,NYer,"$30,878",2017
97,Under the Skin of the City,"$7,412",416,Magn.,"$30,666",2017
98,The Sea is Watching,"$10,500",417,SRep,"$30,577",2017
99,Gang of Roses,"$26,282",418,DEJ,"$30,497",2017

In [170]:
urls = "http://www.boxofficemojo.com/yearly/chart/?page=6&view=releasedate&view2=domestic&yr=" + years_list["years"] + "&p=.htm"

In [171]:
movie_budget_page_6 = []

for i in urls:
    response = rq.post(i)
    doc = BeautifulSoup(response.text, "html.parser")
#     for rows in doc.find_all("tr")[9:67]:
    for rows in doc.find_all("tr")[9:109]:
        try:
            dictionary = {}
            dictionary["Rank"] = rows.find_all("td")[0].text.strip()
            dictionary["Name"] = rows.find_all("td")[1].text.strip()
            dictionary["Studio"] = rows.find_all("td")[2].text.strip()
            dictionary["Total Gross"] = rows.find_all("td")[3].text.strip()
            dictionary["Opening"] = rows.find_all("td")[5].text.strip()
            dictionary["Years"] = 2017 
#             print(rows.find_all("td")[0].text.strip())
            movie_budget_page_6.append(dictionary)
        except:
            print("Failed")
            pass

Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed

In [172]:
df_movie_budget_page_6 = pd.DataFrame(movie_budget_page_6)
df_movie_budget_page_6.head(100)

,Name,Opening,Rank,Studio,Total Gross,Years
0,Independent Spirits,$960,501,Cn4,"$1,551",2017
1,The Ballad of Bering Strait,"$1,232",502,Emr.,"$1,440",2017
2,El Leyton,"$1,332",503,Cn4,"$1,332",2017
3,Exorcism: The Movie,"$1,303",504,Exr.,"$1,303",2017
4,A House on a Hill,$678,505,Abr.,$984,2017
5,Big Shot's Funeral,$529,506,SPC,$820,2017
6,"$9,057,460,265",-,Totals:,-,-,2017
7,"$17,900,119",-,Averages:,-,-,2017
8,Silent Waters,"$1,617",501,FRun,"$7,384",2017
9,Wake,"$6,164",502,Ech.,"$7,212",2017
10,Los Angeles Plays Itself,"$5,005",503,B/F,"$6,945",2017
11,Master of the Game,"$6,554",504,Sun.,"$6,554",2017
12,The Last Place on Earth,"$1,180",505,Pan.,"$6,505",2017
13,It's All About Love,"$2,582",506,Strand,"$6,140",2017
14,Love Object,"$4,492",507,Vita.,"$6,028",2017
15,Klezmer on Fish Street,"$2,628",508,Castle,"$5,724",2017
16,Particles of Truth,"$5,348",509,Da.,"$5,348",2017
17,Bright Future,"$2,755",510,Palm,"$5,166",2017
18,Whore,"$1,964",511,Scre.,"$5,130",2017
19,Home of the Brave (2004),"$3,185",512,Emr.,"$4,874",2017
20,How to Draw a Bunny,"$2,706",513,Palm,"$4,658",2017
21,The Life and Times of Allen Ginsberg (Re-issue),"$1,475",514,NYer,"$4,490",2017
22,Open My Heart,"$2,049",515,Strand,"$4,381",2017
23,The Hillside Strangler,$306,516,Tar.,"$4,143",2017
24,Stella Street,"$2,574",517,Strand,"$4,119",2017
25,Dolls,"$2,067",518,Palm,"$4,067",2017
26,Bandido,"$4,064",519,Inn.,"$4,064",2017
27,Saints and Sinners,"$2,167",520,Avat.,"$3,826",2017
28,My Wife Maurice,"$2,227",521,TLA,"$3,803",2017
29,The Green Butchers,"$2,483",522,NM,"$3,783",2017
30,The Big Animal,"$3,733",523,Mile.,"$3,733",2017
31,"Still, the Children Are Here","$2,210",524,Icar.,"$3,685",2017
32,Brothers in Arms,$658,525,FRun,"$3,664",2017
33,Moog,"$2,227",526,Plx.,"$3,604",2017
34,Cockfight,"$3,200",527,Ech.,"$3,600",2017
35,Tamala 2010,"$3,386",528,Vita.,"$3,386",2017
36,Abouna,"$2,350",529,Leis.,"$3,290",2017
37,The Outskirts,$607,530,Fct.,"$2,797",2017
38,The Child I Never Was,"$1,617",531,Strand,"$2,609",2017
39,Conspiracy of Silence,"$2,598",532,Watch,"$2,598",2017
40,Risk/Reward,"$2,517",533,Org.,"$2,517",2017
41,Swing,"$2,509",534,RMH,"$2,509",2017
42,The Other World,"$1,119",535,Artma,"$2,494",2017
43,Moto X Kids,"$2,462",536,Tag,"$2,462",2017
44,Firedancer,"$2,422",537,Cn4,"$2,422",2017
45,The Road to Love,$867,538,Arab,"$1,714",2017
46,Marathon,"$1,703",539,Cn4,"$1,703",2017
47,Persons of Interest,N/A,540,FRun,"$1,672",2017
48,Rockets Redglare!,"$1,292",541,SmlP,"$1,605",2017
49,What Boys Like,$955,542,"Vsn,","$1,554",2017
50,Free Radicals,"$1,443",543,Kino,"$1,443",2017
51,Shwaas,"$1,042",544,Kath.,"$1,416",2017
52,Big Girls Don't Cry,$682,545,Strand,"$1,238",2017
53,Freeze Frame,"$1,100",546,First,"$1,100",2017
54,Producing Adults,$459,547,Wlfe.,$935,2017
55,800 Bullets,$866,548,TLA,$866,2017
56,Anatomy 2,$383,549,Strand,$623,2017
57,"Jesus, You Know",$604,550,Leis.,$604,2017
58,Tasuma: The Fighter,$281,551,Artma,$479,2017
59,"$9,319,526,494",-,Totals:,-,-,2017
60,"$16,913,841",-,Averages:,-,-,2017
61,Aristide and Endless Revolution,"$2,552",501,FRun,"$6,998",2017
62,Daybreak,"$2,350",502,NM,"$6,995",2017
63,The Aggressives,"$3,769",503,7Art,"$6,533",2017
64,"Magdalena, The Unholy Saint","$6,470",504,Unco,"$6,470",2017
65,"Congo: White King, Red Rubber, Black Death","$3,238",505,Artma,"$6,458",2017
66,Solitude,"$1,480",506,Indic.,"$6,260",2017
67,Emile,"$1,529",507,Castle,"$5,799",2017
68,Sueno,"$4,181",508,SPHE,"$5,729",2017
69,The Roost,"$2,926",509,Vita.,"$5,642",2017
70,Streets of Legend,"$3,769",510,Lions,"$5,471",2017
71,"Peace, Propaganda and the Promised Land","$1,735",511,Arab,"$4,930",2017
72,Perlasca,"$2,281",512,Castle,"$4,780",2017
73,Isn't This a Time! A Tribute to Harold Leventhal,"$2,428",513,7Art,"$4,683",2017
74,My Big Fat Independent Movie,"$4,655",514,BFM,"$4,655",2017
75,Sacred Stage,"$3,724",515,FRun,"$4,410",2017
76,McLibel,"$1,821",516,CLS,"$4,337",2017
77,This Divided State,"$1,653",517,Mino.,"$4,255",2017
78,The Painting,$976,518,Castle,"$4,115",2017
79,A Hole in My Heart,"$1,720",519,NM,"$3,784",2017
80,The Helix... Loaded,"$3,500",520,Rom.,"$3,700",2017
81,Happy Here and Now,"$1,867",521,IFC,"$3,574",2017
82,The Rider Named Death,"$2,438",522,Kino,"$3,375",2017
83,I Love Your Work,"$2,580",523,Think,"$3,264",2017
84,Sex Sells: The Making of Touche,"$2,386",524,HB,"$3,252",2017
85,Nowhere Man,$173,525,FRun,"$3,105",2017
86,Unveiled,"$3,025",526,Wlfe.,"$3,025",2017
87,15,$633,527,Pict.,"$3,013",2017
88,Stolen Childhoods,"$2,996",528,Bal.,"$2,996",2017
89,Three Days of Rain,"$2,841",529,RA,"$2,841",2017
90,The Optimists: The Story of the Rescue of the Bulgarian Jews from the Holocaust,"$2,377",530,Castle,"$2,377",2017
91,The Overture,$825,531,Kino,"$2,254",2017
92,Side Effects,"$2,216",532,Hum.,"$2,216",2017
93,Steal Me,"$1,600",533,Cnv.,"$1,967",2017
94,With God on Our Side: George W. Bush...,$563,534,Lum.,"$1,884",2017
95,She's One of Us,$996,535,Leis.,"$1,870",2017
96,The Boat Is Full (re-issue),"$1,016",536,Castle,"$1,718",2017
97,Twin Sisters,"$1,207",537,Mira.,"$1,563",2017
98,Making Grace,$456,538,FRun,"$1,496",2017
99,The Letter: An American Town and the 'Somali Invasion',$789,539,Arab,"$1,479",2017

In [173]:
urls = "http://www.boxofficemojo.com/yearly/chart/?page=7&view=releasedate&view2=domestic&yr=" + years_list["years"] + "&p=.htm"

In [174]:
movie_budget_page_7 = []

for i in urls:
    response = rq.post(i)
    doc = BeautifulSoup(response.text, "html.parser")
#     for rows in doc.find_all("tr")[9:67]:
    for rows in doc.find_all("tr")[9:109]:
        try:
            dictionary = {}
            dictionary["Rank"] = rows.find_all("td")[0].text.strip()
            dictionary["Name"] = rows.find_all("td")[1].text.strip()
            dictionary["Studio"] = rows.find_all("td")[2].text.strip()
            dictionary["Total Gross"] = rows.find_all("td")[3].text.strip()
            dictionary["Opening"] = rows.find_all("td")[5].text.strip()
            dictionary["Years"] = 2017 
#             print(rows.find_all("td")[0].text.strip())
            movie_budget_page_7.append(dictionary)
        except:
            print("Failed")
            pass

Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed

In [175]:
df_movie_budget_page_7 = pd.DataFrame(movie_budget_page_7)
df_movie_budget_page_7.head(100)

,Name,Opening,Rank,Studio,Total Gross,Years
0,The Trouble with Men and Women,$375,601,IFC,$967,2017
1,In Her Line of Fire,$232,602,Reg.,$884,2017
2,Doing Time for Patsy Cline,$831,603,Oilr.,$831,2017
3,Issues,$783,604,Bllz.,$783,2017
4,Uncut,$390,605,Strand,$762,2017
5,A New Day in Old Sana'a,$401,606,Arab,$737,2017
6,Serum,N/A,607,Arv.,$440,2017
7,Zyzzyx Road,$20,608,Reg.,$30,2017
8,"$9,214,401,719",-,Totals:,-,-,2017
9,"$15,155,266",-,Averages:,-,-,2017
10,The Prisoner or: How I Planned to Kill Tony Blair,"$2,194",601,RedE,"$3,103",2017
11,Los Muertos,"$1,758",602,Fct.,"$3,027",2017
12,Funny Money,"$1,839",603,Think,"$2,844",2017
13,Half Moon,"$1,126",604,Strand,"$2,528",2017
14,He Was a Quiet Man,"$2,431",605,Mitro.,"$2,431",2017
15,Looking for an Icon,"$1,760",606,Icar.,"$2,393",2017
16,Chronicle of an Escape (Cronica de una fuga),"$1,307",607,IFC,"$2,370",2017
17,You're Gonna Miss Me,"$1,340",608,Palm,"$2,324",2017
18,Adrift in Manhattan,"$2,099",609,Scre.,"$2,099",2017
19,Badland,"$1,924",610,ArcA.,"$1,924",2017
20,Greg & Gentillon,"$1,913",611,All.,"$1,913",2017
21,Oswald's Ghost,"$1,796",612,7Art,"$1,796",2017
22,Divine Intervention (2007),$856,613,Bllz.,"$1,485",2017
23,Out of the Blue,$728,614,IFC,"$1,477",2017
24,'Tis Autumn: The Search for Jackie Paris,"$1,476",615,OutF,"$1,476",2017
25,Unborn in the USA,"$1,035",616,FRun,"$1,475",2017
26,Four Lane Highway,$955,617,SkyI,"$1,393",2017
27,The Dog Problem,$914,618,Think,"$1,344",2017
28,Adam's Apples,"$1,305",619,Outs,"$1,305",2017
29,Eleven Men Out,"$1,302",620,Reg.,"$1,302",2017
30,The Trials of Darryl Hunt,$619,621,Think,"$1,217",2017
31,Looking for Cheyenne,$165,622,Reg.,$973,2017
32,Beyond Hatred,$533,623,FRun,$949,2017
33,It's a Boy Girl Thing,$848,624,All.,$848,2017
34,Flakes,$311,625,IFC,$778,2017
35,The Sugar Curtain,$582,626,Icar.,$582,2017
36,Notes on Marie Menken,$577,627,Icar.,$577,2017
37,Falling,$509,628,Kino,$509,2017
38,The Last Door,$488,629,All.,$488,2017
39,The Marsh,$336,630,All.,$336,2017
40,Intervention,$279,631,All.,$279,2017
41,"$9,690,698,475",-,Totals:,-,-,2017
42,"$15,357,684",-,Averages:,-,-,2017
43,Disfigured,$585,601,CLS,$829,2017
44,Christmas in Wonderland,$689,602,YFG,$689,2017
45,The Rise and Fall of Miss Thang,N/A,603,LavH,$581,2017
46,A Bloody Aria,$249,604,ImAs,$518,2017
47,Canary,$504,605,ImAs,$504,2017
48,Back to Normandy,N/A,606,Kino,$503,2017
49,Rome & Jewel,$470,607,Emr.,$470,2017
50,"$9,698,009,486",-,Totals:,-,-,2017
51,"$15,976,951",-,Averages:,-,-,2017
52,Illegal (2011),$404,601,FM,$651,2017
53,A Good Day to Die,N/A,602,AM,$573,2017
54,"$10,113,802,839",-,Totals:,-,-,2017
55,"$16,800,337",-,Averages:,-,-,2017
56,Last Ride,$838,601,MBox,"$6,853",2017
57,In Our Nature,"$4,378",602,Cdgm.,"$6,543",2017
58,Windfall,"$1,780",603,FRun,"$6,504",2017
59,The Beat Hotel,"$1,458",604,FRun,"$6,480",2017
60,Tonight You're Mine,"$2,144",605,RAtt.,"$6,255",2017
61,Crazy Eyes,"$3,259",606,Strand,"$6,141",2017
62,The Last Fall,"$6,100",607,TFO,"$6,100",2017
63,The Miners' Hymns,"$3,217",608,Icar.,"$6,051",2017
64,Las Acacias,"$6,000",609,OutF,"$6,000",2017
65,American Animal,"$5,928",610,Scre.,"$5,928",2017
66,Buzzkill,N/A,611,Indic.,"$5,860",2017
67,Sushi: The Global Catch,$516,612,AM,"$5,757",2017
68,Save the Date,"$3,755",613,IFC,"$5,719",2017
69,Bookers Place,"$2,455",614,Trib.,"$5,549",2017
70,Young and Wild,"$3,798",615,IFC,"$5,514",2017
71,Universal Soldier: Day of Reckoning,"$3,181",616,Magn.,"$5,460",2017
72,The Good Doctor,"$3,180",617,Magn.,"$5,206",2017
73,Liar's Autobiography,"$5,102",618,BSM,"$5,102",2017
74,Downtown Express,"$3,474",619,ICir,"$5,010",2017
75,Bringing Up Bobby,"$1,005",620,Mont.,"$4,975",2017
76,Tomorrow When the War Began,"$3,172",621,Free,"$4,936",2017
77,Brake,"$4,330",622,IFC,"$4,876",2017
78,A Man Vanishes (2012 re-release),"$1,576",623,Icar.,"$4,829",2017
79,Breathing,$949,624,KL,"$4,630",2017
80,Newlyweds,"$4,584",625,Trib.,"$4,584",2017
81,Art Is... The Permanent Revolution,"$2,718",626,FRun,"$4,291",2017
82,Yangsi,N/A,627,KL,"$4,008",2017
83,The Moth Diaries,"$2,276",628,IFC,"$3,838",2017
84,Free Radicals: A History of Experimental Film,"$1,350",629,KL,"$3,804",2017
85,They Come to America,"$3,775",630,C/360,"$3,775",2017
86,Bad Blood the Hunger,"$1,872",631,GA,"$3,731",2017
87,Pickin & Grinnin,"$3,003",632,HLM,"$3,613",2017
88,The Day I Saw Your Heart,"$2,810",633,FM,"$3,546",2017
89,Loosies,$808,634,IFC,"$3,519",2017
90,Cirkus Columbia,"$1,284",635,Strand,"$3,457",2017
91,Vamps,$548,636,Anch.,"$3,361",2017
92,Sleepless Night,"$2,106",637,Trib.,"$3,358",2017
93,After the Wizard,"$2,527",638,BGP,"$3,184",2017
94,Apart (2012),"$3,161",639,Truly,"$3,161",2017
95,ATM,"$2,034",640,IFC,"$3,010",2017
96,About Cherry,"$2,760",641,IFC,"$3,003",2017
97,Perfect Sense,"$1,567",642,IFC,"$2,959",2017
98,Cheerful Weather for the Wedding,$727,643,IFC,"$2,651",2017
99,Carl,"$2,592",644,ALP,"$2,592",2017

In [176]:
urls = "http://www.boxofficemojo.com/yearly/chart/?page=8&view=releasedate&view2=domestic&yr=" + years_list["years"] + "&p=.htm"

In [177]:
movie_budget_page_8 = []

for i in urls:
    response = rq.post(i)
    doc = BeautifulSoup(response.text, "html.parser")
#     for rows in doc.find_all("tr")[9:67]:
    for rows in doc.find_all("tr")[9:109]:
        try:
            dictionary = {}
            dictionary["Rank"] = rows.find_all("td")[0].text.strip()
            dictionary["Name"] = rows.find_all("td")[1].text.strip()
            dictionary["Studio"] = rows.find_all("td")[2].text.strip()
            dictionary["Total Gross"] = rows.find_all("td")[3].text.strip()
            dictionary["Opening"] = rows.find_all("td")[5].text.strip()
            dictionary["Years"] = 2017 
#             print(rows.find_all("td")[0].text.strip())
            movie_budget_page_8.append(dictionary)
        except:
            print("Failed")
            pass

Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed
Failed

In [178]:
df_movie_budget_page_8 = pd.DataFrame(movie_budget_page_8)
df_movie_budget_page_8.head(100)

,Name,Opening,Rank,Studio,Total Gross,Years
0,A People Uncounted,$390,701,FRun,$930,2017
1,Jackpot,$806,702,DR,$806,2017
2,Grand Depart,$339,703,Rialto,$677,2017
3,Skinless,$168,704,PPF,$400,2017
4,Cinemanovels,N/A,705,Mont.,$398,2017
5,"Mummy, I'm a Zombie",N/A,706,P4,$120,2017
6,"$10,436,015,176",-,Totals:,-,-,2017
7,"$14,781,891",-,Averages:,-,-,2017
8,United Passions,$607,701,Scre.,$607,2017
9,The Chambermaid,N/A,702,FM,$315,2017
10,Lou! Journal infime,$88,703,Distrib.,$287,2017
11,Paranoid Girls,$54,704,N/A,$78,2017
12,Confession of a Child of the Century,$68,705,Cohen,$74,2017
13,"$11,098,722,111",-,Totals:,-,-,2017
14,"$15,742,868",-,Averages:,-,-,2017
15,Among the Believers,"$1,900",701,FRun,"$4,189",2017
16,The Hollow,"$2,848",702,Uncork'd,"$3,755",2017
17,The Last Film Festival,N/A,703,Mont.,"$3,558",2017
18,The Loving Story (2016 re-release),N/A,704,Icar.,"$3,518",2017
19,Restored Me (Masters Media),"$1,316",705,Masters,"$3,428",2017
20,Burning Bodhi,"$1,474",706,Mont.,"$3,289",2017
21,In Harmony,$809,707,Distrib.,"$3,144",2017
22,Best and Most Beautiful Things,"$1,591",708,FRun,"$3,016",2017
23,A Kind of Murder,$978,709,Magn.,"$2,915",2017
24,The Professor: Tai Chi's Journey West,"$1,744",710,FRun,"$2,852",2017
25,White Lies,"$1,740",711,Artma,"$2,760",2017
26,Mekong Hotel,$999,712,Strand,"$2,502",2017
27,Homeland,$560,713,KL,"$2,491",2017
28,From the East,$564,714,Icar.,"$2,436",2017
29,"1,000 Rupee Note","$1,697",715,KL,"$2,404",2017
30,The Ghosts of Johnson Woods,N/A,716,DWOES,"$2,335",2017
31,Memoria,$47,717,Mont.,"$2,242",2017
32,The Vigilante Diaries,"$1,650",718,Anch.,"$1,991",2017
33,The Watermelon Woman (20th Anniversary / 2K HD Restoration),$774,719,FRun,"$1,989",2017
34,A Beautiful Now,$148,720,Mont.,"$1,714",2017
35,In Her Name (Au nom de ma fille),N/A,721,Distrib.,"$1,623",2017
36,Miss India America,$687,722,MarVista,"$1,598",2017
37,Level Up,N/A,723,FB,"$1,469",2017
38,Hyena Road,"$1,430",724,Gold.,"$1,430",2017
39,The Silence of Mark Rothko,$268,725,Icar.,"$1,422",2017
40,A Small Good Thing,"$1,196",726,KL,"$1,196",2017
41,Yalom's Cure,$684,727,FRun,"$1,164",2017
42,Officer Downe,$470,728,Magn.,$850,2017
43,Next Time I'll Aim for the Heart,$310,729,Distrib.,$815,2017
44,The Student and Mr. Henri,$486,730,Distrib.,$761,2017
45,Down By Love,$390,731,Distrib.,$675,2017
46,The Pit (2016 re-release),N/A,732,KL,$560,2017
47,Green is Gold,$273,733,Gold.,$455,2017
48,Hannah: Buddhism's Untold Journey,N/A,734,KL,$396,2017
49,News From Planet Mars,$24,735,KL,$310,2017
50,Satanic,$205,736,Magn.,$252,2017
51,"$11,370,365,408",-,Totals:,-,-,2017
52,"$15,448,866",-,Averages:,-,-,2017
53,Detour,$145,701,Magn.,"$1,788",2017
54,Almost Friends,N/A,702,Orion,"$1,481",2017
55,The Outcasts,"$1,008",703,Swen,"$1,455",2017
56,Forest for the Trees (2017 re-release),N/A,704,FM,"$1,410",2017
57,It's Not Yet Dark,$811,705,FR,"$1,227",2017
58,A Different American Dream,$848,706,FRun,"$1,172",2017
59,The Penguin Counters,$976,707,FRun,$976,2017
60,Extraordinary Ordinary People,$744,708,FRun,$880,2017
61,Amityville: The Awakening,$742,709,W/Dim.,$742,2017
62,Max & Leon,N/A,710,Distrib.,$543,2017
63,The Student,N/A,711,UTMW,$512,2017
64,2:22,$294,712,Magn.,$422,2017
65,"$9,741,168,574",-,Totals:,-,-,2017
66,"$13,681,417",-,Averages:,-,-,2017

In [181]:
df_movie_budget_years_append = df_movie_budget_years.append(df_movie_budget_page_2)
df_movie_budget_years_append = df_movie_budget_years_append.append(df_movie_budget_page_3)
df_movie_budget_years_append = df_movie_budget_years_append.append(df_movie_budget_page_4)
df_movie_budget_years_append = df_movie_budget_years_append.append(df_movie_budget_page_5)
df_movie_budget_years_append = df_movie_budget_years_append.append(df_movie_budget_page_6)
df_movie_budget_years_append = df_movie_budget_years_append.append(df_movie_budget_page_7)
df_movie_budget_years_append = df_movie_budget_years_append.append(df_movie_budget_page_8)

In [182]:
df_movie_budget_years_append.head()

                   Name      Opening Rank Studio   Total Gross  Years
0         Jurassic Park  $47,026,828    1   Uni.  $357,067,947   2017
1        Mrs. Doubtfire  $20,468,847    2    Fox  $219,195,243   2017
2          The Fugitive  $23,758,855    3     WB  $183,875,760   2017
3              The Firm  $25,400,000    4   Par.  $158,348,367   2017
4  Sleepless in Seattle  $17,253,733    5   TriS  $126,680,884   2017

In [183]:
df_movie_budget_years_append.tail()

              Name Opening       Rank    Studio Total Gross  Years
62      Max & Leon     N/A        710  Distrib.        $543   2017
63     The Student     N/A        711      UTMW        $512   2017
64            2:22    $294        712     Magn.        $422   2017
65  $9,741,168,574       -    Totals:         -           -   2017
66     $13,681,417       -  Averages:         -           -   2017

In [184]:
df_movie_budget_years_append.to_csv("movie_budget_years.csv")