In [1]:
import pandas as pd
import re

In [3]:
Star_Wars_Gender = pd.read_csv("Star_Wars_Gender.csv")

In [7]:
Star_Wars_Gender_grouped = Star_Wars_Gender.groupby(["Gender", "Movie"])["Word_count"].sum().reset_index()

In [16]:
Star_Wars_Gender_grouped = Star_Wars_Gender_grouped.reset_index()

In [20]:
Star_Wars_Gender_grouped = Star_Wars_Gender_grouped.sort_values(by = "Movie")

In [25]:
Star_Wars_Gender_grouped_sum = Star_Wars_Gender_grouped.groupby("Movie")["Word_count"].sum().reset_index()

In [31]:
Star_Wars_Gender_grouped_sum.columns = ["Movie", "total"]

In [32]:
Star_Wars_Gender_grouped_merged = Star_Wars_Gender_grouped.merge(Star_Wars_Gender_grouped_sum, left_on = "Movie", right_on = "Movie")

In [38]:
Star_Wars_Gender_grouped_merged["proportion"] = Star_Wars_Gender_grouped_merged["Word_count"] / Star_Wars_Gender_grouped_merged["total"]* 100

In [39]:
Star_Wars_Gender_grouped_merged

    index  Gender                    Movie  Word_count  total  proportion
0      16  Robots               A New Hope        1841  13857   13.285704
1       2  Female               A New Hope         837  13857    6.040268
2       9    Male               A New Hope       11179  13857   80.674028
3       0   Droid     Attack of the Clones         389  10728    3.626025
4      10    Male     Attack of the Clones        7070  10728   65.902312
5       3  Female     Attack of the Clones        3269  10728   30.471663
6      11    Male       Return of the Jedi        4226   5619   75.209112
7      17  Robots       Return of the Jedi         937   5619   16.675565
8       4  Female       Return of the Jedi         456   5619    8.115323
9       5  Female      Revenge of the Sith        1456  12890   11.295578
10     12    Male      Revenge of the Sith       10784  12890   83.661753
11     18  Robots      Revenge of the Sith         650  12890    5.042669
12      6  Female  The Empire Strikes Back         780   7763   10.047662
13     19  Robots  The Empire Strikes Back        1219   7763   15.702692
14     13    Male  The Empire Strikes Back        5764   7763   74.249646
15      7  Female        The Force Awakens        1684   6633   25.388210
16     14    Male        The Force Awakens        4740   6633   71.460877
17     20  Robots        The Force Awakens         209   6633    3.150912
18      8  Female       The Phantom Menace        1270   9206   13.795351
19     15    Male       The Phantom Menace        7763   9206   84.325440
20      1   Droid       The Phantom Menace         173   9206    1.879209