In [1]:
import requests as rq
from bs4 import BeautifulSoup
import pandas as pd
import re

In [4]:
years = [2000,2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,2013, 2014, 2015, 2016, 2017, 2018]

In [5]:
years_df = pd.DataFrame(years)
years_df.columns = ["Years"]
years_df["Years"] = years_df["Years"].astype(str)

In [6]:
years_df

   Years
0   2000
1   2001
2   2002
3   2003
4   2004
5   2005
6   2006
7   2007
8   2008
9   2009
10  2010
11  2011
12  2012
13  2013
14  2014
15  2015
16  2016
17  2017
18  2018

In [7]:
urls = "https://www.pro-football-reference.com/years/" + years_df["Years"] + "/#all_AFC"

In [9]:
pd.set_option('max_colwidth',100)

In [15]:
urls

0     https://www.pro-football-reference.com/years/2000/#all_AFC
1     https://www.pro-football-reference.com/years/2001/#all_AFC
2     https://www.pro-football-reference.com/years/2002/#all_AFC
3     https://www.pro-football-reference.com/years/2003/#all_AFC
4     https://www.pro-football-reference.com/years/2004/#all_AFC
5     https://www.pro-football-reference.com/years/2005/#all_AFC
6     https://www.pro-football-reference.com/years/2006/#all_AFC
7     https://www.pro-football-reference.com/years/2007/#all_AFC
8     https://www.pro-football-reference.com/years/2008/#all_AFC
9     https://www.pro-football-reference.com/years/2009/#all_AFC
10    https://www.pro-football-reference.com/years/2010/#all_AFC
11    https://www.pro-football-reference.com/years/2011/#all_AFC
12    https://www.pro-football-reference.com/years/2012/#all_AFC
13    https://www.pro-football-reference.com/years/2013/#all_AFC
14    https://www.pro-football-reference.com/years/2014/#all_AFC
15    https://www.pro-football-reference.com/years/2015/#all_AFC
16    https://www.pro-football-reference.com/years/2016/#all_AFC
17    https://www.pro-football-reference.com/years/2017/#all_AFC
18    https://www.pro-football-reference.com/years/2018/#all_AFC
Name: Years, dtype: object

In [70]:
list_nfl_data = []

for i in urls:
    response = rq.post(i)
    doc = BeautifulSoup(response.text, "html.parser")
    for n in doc.find_all("tr")[1:]:
        dictionary = {}
        Tm = n.find("a")
        if Tm is not None and len(Tm) > 0:
            dictionary["Team"] = Tm.text.strip()
        W = n.find(attrs = {"data-stat": "wins"})
        if W is not None and len(W) > 0:
            dictionary["W"] = W.text.strip()
        L = n.find(attrs = {"data-stat": "losses"})
        if L is not None and len(L) > 0:
            dictionary["L"] = L.text.strip()
        W_L = n.find(attrs = {"data-stat": "win_loss_perc"})
        if W_L is not None and len(W_L) > 0:
            dictionary["W_L"] = W_L.text.strip()
        points = n.find(attrs = {"data-stat": "points"})
        if points is not None and len(points) > 0:
            dictionary["points"] = points.text.strip()
        points_opp = n.find(attrs = {"data-stat": "points_opp"})
        if points_opp is not None and len(points_opp) > 0:
            dictionary["points_opp"] = points_opp.text.strip()
        mov = n.find(attrs = {"data-stat": "mov"})
        if mov is not None and len(mov) > 0:
            dictionary["MOV"] = mov.text.strip()
        points_diff = n.find(attrs = {"data-stat": "points_diff"})
        if points_diff is not None and len(points_diff) > 0:
            dictionary["points_diff"] = points_diff.text.strip()
        sos = n.find(attrs = {"data-stat": "sos_total"})
        if sos is not None and len(sos) > 0:
            dictionary["sos"] = sos.text.strip()
        srs = n.find(attrs = {"data-stat": "srs_total"})
        if srs is not None and len(srs) > 0:
            dictionary["srs"] = srs.text.strip()
        OSRS = n.find(attrs = {"data-stat": "srs_offense"})
        if OSRS is not None and len(OSRS) > 0:
            dictionary["OSRS"] = OSRS.text.strip()
        DSRS = n.find(attrs = {"data-stat": "srs_defense"})
        if DSRS is not None and len(DSRS) > 0:
            dictionary["DSRS"] = DSRS.text.strip()
        dictionary["Year"] = i
        list_nfl_data.append(dictionary)

In [71]:
df = pd.DataFrame(list_nfl_data)

In [73]:
df = df.dropna()

In [74]:
df.head()

,DSRS,L,MOV,OSRS,Team,W,W_L,Year,points,points_diff,points_opp,sos,srs
1,7.1,5,6.1,0.0,Miami Dolphins,11,.688,https://www.pro-football-reference.com/years/2000/#all_AFC,323,97,226,1.0,7.1
2,0.8,6,6.4,7.1,Indianapolis Colts,10,.625,https://www.pro-football-reference.com/years/2000/#all_AFC,429,103,326,1.5,7.9
3,2.2,7,0.0,1.4,New York Jets,9,.563,https://www.pro-football-reference.com/years/2000/#all_AFC,321,0,321,3.5,3.5
4,-0.5,8,-2.2,0.5,Buffalo Bills,8,.500,https://www.pro-football-reference.com/years/2000/#all_AFC,315,-35,350,2.2,0.0
5,0.2,11,-3.9,-2.7,New England Patriots,5,.313,https://www.pro-football-reference.com/years/2000/#all_AFC,276,-62,338,1.4,-2.5

In [75]:
df.tail()

,DSRS,L,MOV,OSRS,Team,W,W_L,Year,points,points_diff,points_opp,sos,srs
767,-4.6,11,-4.3,2.0,Tampa Bay Buccaneers,5,.313,https://www.pro-football-reference.com/years/2018/#all_AFC,396,-68,464,1.7,-2.6
769,-1.1,3,8.9,9.5,Los Angeles Rams,13,.813,https://www.pro-football-reference.com/years/2018/#all_AFC,527,143,384,-0.4,8.5
770,1.5,6,5.1,3.0,Seattle Seahawks,10,.625,https://www.pro-football-reference.com/years/2018/#all_AFC,428,81,347,-0.6,4.5
771,-3.1,12,-5.8,-2.5,San Francisco 49ers,4,.250,https://www.pro-football-reference.com/years/2018/#all_AFC,342,-93,435,0.3,-5.5
772,-1.9,13,-12.5,-9.6,Arizona Cardinals,3,.188,https://www.pro-football-reference.com/years/2018/#all_AFC,225,-200,425,1.0,-11.5

In [78]:
df["Year"] = df["Year"].str.split("/", 5, expand = True)[4]

In [79]:
df.head()

,DSRS,L,MOV,OSRS,Team,W,W_L,Year,points,points_diff,points_opp,sos,srs
1,7.1,5,6.1,0.0,Miami Dolphins,11,.688,2000,323,97,226,1.0,7.1
2,0.8,6,6.4,7.1,Indianapolis Colts,10,.625,2000,429,103,326,1.5,7.9
3,2.2,7,0.0,1.4,New York Jets,9,.563,2000,321,0,321,3.5,3.5
4,-0.5,8,-2.2,0.5,Buffalo Bills,8,.500,2000,315,-35,350,2.2,0.0
5,0.2,11,-3.9,-2.7,New England Patriots,5,.313,2000,276,-62,338,1.4,-2.5

In [80]:
df.to_csv("NFL_Standings.csv")